export default {
Reserve_the_right_choice: "مساحة رقمية للمعارض",
Email: "📧البريد الإلكتروني",
Password: "🔑كلمة المرور",
Confirm_Password: "🔑تأكيد كلمة المرور",
Sign_Up: "إنشاء حساب",
Log_In: "تسجيل الدخول",
Click_on_the_verification_link_that_is_sent_to_your_registered_email_ID: "لتفعيل البريد الإلكتروني، اضغطي على الرابط المرسل إليكِ",
CLOSE: "إغلاق",
Forgot_Password: "إعادة تعيين كلمة المرور؟",
Verify_Email: "تفعيل البريد الإلكتروني",
Reset_Password: "إعادة تعيين كلمة المرور",
Back: "عودة",
Password_reset: "لإعادة تعيين كلمة المرور،\nاضغطي على الرابط المرسل إليكِ",
Accept: "قبول",
Decline: "رفض",
jiffybooklegal: "الشروط والسياسات",
JiffyBook: "جيفيبوك",
LOCATION_SETUP: "تحديد الموقع",
Search_your_location: "البحث عن موقع",
SAVE_LOCATION: "حفظ",
PROFILE_SETUP: "إنشاء ملفي الشخصي",
Title: "أنا . . .",
Ms: "امرأة",
Mr: "رجل",
Mrs: "سيدة",
Name: "👤الاسم",
Phone: "📞رقم الهاتف",
SAVE_PROFILE: "حفظ",
DELETE_ACCOUNT: "حذف الحساب",
Delete_message1: "هذا أمر محزن😢",
Delete_message2: "هل تريدين حقاً حذف حسابكِ؟ لمعرفة البيانات التي سيتم حذفها، يرجى قراءة الشروط والسياسة.",
Yes: "نعم",
No: "لا",
Change_admin: "انقل ملكية معرضك وحاول مرة أخرى",
My_Location: "موقعي",
Service: "خدمة",
Event: "فعالية",
Venue: "موقع",
Space: "مساحة",
Support: "دعم",
Training: "تدريب",
Art: "فن",
Register_a_business: "إنشاء جيفيجاليري",
exit_message: "هل تريد إغلاق التطبيق؟",
Sure: "بالتأكيد!",
Notyet: "ليس بعد",
Home: "الرئيسية",
Account: "الحساب",
Booking: "الحجز",
Notification: "التنبيهات",
Business: "جيفيجاليري",
About_us: "حول",
Sign_out: "تسجيل الخروج",
Aboutus2: "إن دريمر، إستونيا",
Aboutus4: "عرض",
Aboutus5: "شروط الخدمة وسياسة الخصوصية",
Aboutus6: "زيارة",
Aboutus7: "موقع جيفيبوك الإلكتروني",
Aboutus8: "لمزيد من المعلومات",
Nobusiness: "عذراً! لا يوجد شيء هنا.",
Click_to_ADD: "اضغطي على + للإضافة",
BUSINESS_NAME: "اسم المعرض (٥٠ حرفاً)",
Opens_at: "ساعة الفتح",
Closes_at: "ساعة الإغلاق",
Add_success: "تمت الإضافة بنجاح!",
ADD_BUSINESS: "إضافة جيفيجاليري",
Recommendation: "تضمن اسم المكان لجعله فريداً.",
Note: "للمعارض ذات المواقع المتعددة، قم بإنشاء معرض لكل موقع.",
Business_Segment: "المخطط",
Select: "اختر",
Doctor: "طبيب",
Hospital: "مستشفى",
Consultant: "مستشار",
Parking: "موقف سيارات",
Recreation: "ترفيه",
Select_business_segment: "اختر",
Business_Category: "اختر الكتالوجات",
Business_Sub_category: "اختر مسار الطلب",
Reservation_Item: "الكتالوج",
Selected: "مختار",
Next: "التالي",
Start_Date: "بداية فترة الحجز",
End_Date: "نهاية فترة الحجز",
Exclude_Holiday: "إضافة عطلات",
Holiday_List: "قائمة العطلات",
Agent_email: "📧بريد الوكيل",
Optional: "(اختياري)",
Business_Admin: "👤اسم التواصل",
Business_Email: "📧بريد التواصل",
Business_Phone: "هاتف التواصل",
Business_Logo_Image: "الشعار (استخدم صورة مربعة لأفضل النتائج)",
Business_Profile_Photos: "الصور الإعلانية (استخدم صوراً مربعة لأفضل النتائج)",
uploadphotos10: "الحد الأقصى: ١٠ صور",
Business_Location: "الموقع",
DONE: "حفظ",
Register_popup1: "جاري إنشاء جيفيجاليري - ",
Register_popup2: "هل توافق على الشروط والسياسة؟",
Terms: "الشروط والسياسة",
CANCEL: "إلغاء",
I_AGREE: "قبول",
BUSINESS_HOME: "رئيسية المعرض",
RESERVATION_SLOT: "الفترات الزمنية",
RESERVATION_ITEM: "الكتالوج",
BUSINESS_OFFER: "العروض الترويجية",
BUSINESS_STAFF: "الفريق",
MANAGE_PAYMENT: "المالية",
MANAGE_RESERVATION: "الحجوزات / الطلبات",
UPDATE_BUSINESS: "تحديث المعرض",
Enddate_popup: "لا يمكنك تقديم تاريخ الانتهاء للخلف",
Release_day: "قم بإلغاء حجوزات هذا اليوم ثم حاول مرة أخرى",
Do_you_want_to_update: "هل تريد التحديث",
information: "البيانات؟",
Update_success: "تم التحديث بنجاح!",
Not_authorized_to_delete: "ليس لديك الصلاحية للحذف.",
Do_you_want_to_delete: "هل تريد حذف",
Delete_success: "تم الحذف بنجاح!",
Release_business: "قم بإلغاء حجوزات هذا المعرض ثم حاول مرة أخرى",
BUSINESS_PROFILE: "الملف الشخصي",
Business_Description: "وصف المعرض",
Business_Website: "موقع المعرض الإلكتروني",
profile: "؟",
RESERVATION_SLOT1: "الفترة الزمنية",
No_reservation_slot_added: "عذراً! لا يوجد شيء هنا.",
Start_Time: "وقت البدء",
End_Time: "وقت الانتهاء",
ADD_RESERVATION_SLOT: "إضافة فترة",
Slot_NAME: "معرف الفترة",
Do_you_want_to_add: "هل تريد الإضافة",
slot_information: "البيانات؟",
UPDATE_RESERVATION_SLOT: "تحديث معلومات الفترة",
Slot_cannot_be_deleted: "لا يمكنك حذف هذا! يجب وجود فترة واحدة على الأقل.",
slot: "البيانات؟",
Release_slot: "قم بإلغاء حجوزات هذه الفترة ثم حاول مرة أخرى",
No_reservation_item_added: "عذراً! لا يوجد شيء هنا. أضف فترة زمنية واحدة على الأقل قبل إضافة وحدة",
Count_per_slot: "التوفر",
Cost1: "التكلفة",
ADD_RESERVATION_ITEM: "إضافة وحدة",
Count_Available: "التوفر",
Custom_Name: "اسم مخصص",
Limit_Per_Booking: "الحد الأقصى لكل حجز",
Item_Description: "الوصف\nالحد الأقصى: ١٢٨ حرفاً",
Upload_photos5: "الحد الأقصى: ٥ صور",
Specific_time: "الفترات الزمنية",
Specific_staff: "الفريق",
Available_From: "متاح من",
Available_Till: "متاح حتى",
Exclude_Date: "إضافة عطلات",
Excluded_Date: "قائمة العطلات",
UPDATE_RESERVATION_ITEM: "تحديث معلومات الوحدة",
Release_item: "قم بإلغاء حجوزات هذه الوحدة ثم حاول مرة أخرى",
BUSINESS_STAFF1: "الفريق",
No_business_staff_added: "عذراً! لا يوجد شيء هنا.",
Admin: "مسؤول عام",
Staff_Email: "📧البريد الإلكتروني",
Role: "الدور",
ADD_BUSINESS_STAFF: "إضافة عضو",
Email_not_registered: "لم يتم العثور على مستخدم بهذا البريد",
Do_you_want_to_continue: "هل ترغب في الاستمرار",
UPDATE_BUSINESS_STAFF: "تحديث معلومات العضو",
Staff_message3: "هذه البيانات؟",
BUSINESS_OFFER1: "العروض الترويجية",
No_business_offer_added: "عذراً! لا يوجد شيء هنا.",
Offer_Name: "العنوان",
Discount: "نسبة الخصم %",
Max_Discount: "حد الخصم",
ADD_BUSINESS_OFFER: "إضافة عرض ترويجي",
Offer_Description: "الشعار اللفظي",
Expires_On: "تاريخ الانتهاء",
Select_your_ad_template: "صورة إعلانية",
Publish_this_ad: "نشر للعملاء",
Preview: "معاينة",
UPDATE_BUSINESS_OFFER: "تحديث معلومات العرض",
Offer: "هذه البيانات؟",
No_location: "عذراً! لا يوجد شيء هنا.",
No_selection: "عذراً! لا يوجد شيء هنا.",
Miles: " أميال",
Reviews: " تقييمات",
Loading1: "جاري التحميل . . . ",
Services: "خدمات",
Events: "فعاليات",
Doctors: "أطباء",
Hospitals: "مستشفيات",
Venues: "مواقع",
Spaces: "مساحات",
Supports: "دعم",
Consultants: "مستشارون",
Trainings: "تدريبات",
Arts: "فنون",
Loading2: "خيارات حولك",
Booking_open: "بداية فترة الحجز",
View_Profile: "فتح الملف الشخصي",
RUSH: "مستعجل",
BOOK: "حجز",
SOON: "قريباً",
Today: "اليوم",
Tomorrow: "غداً",
Sunday: "الأحد",
Monday: "الاثنين",
Tuesday: "الثلاثاء",
Wednesday: "الأربعاء",
Thursday: "الخميس",
Friday: "الجمعة",
Saturday: "السبت",
Soldout: "ممتلئ",
No_slots_for_booking: "عذراً! لا يوجد شيء هنا.",
No_reservation: "🛒ستظهر طلباتكِ هنا",
No_slots_available: "عذراً! لا يوجد شيء هنا.",
Click_to_navigate: "اضغطي لـ\nالتنقل",
No_profile_description: "لا يوجد وصف للملف الشخصي",
Available_offers: "اختاري العرض",
No_offer_available: "لا توجد عروض ترويجية",
Offer_discount: "نسبة الخصم %",
Offer_maximum: "الحد الأقصى للخصم",
Book1: "حجز",
You_will_save: "ستوفرين",
Avail_Offers: "تطبيق عرض",
None: "لا يوجد",
No_offer_selected: "لا يوجد عرض",
MY_BOOKING: "حجزي",
No_booking: "عذراً! لا يوجد شيء هنا.",
RESERVED: "تم الحجز",
OCCUPIED: "✨تم تسجيل الحضور",
CALLED_OFF1: "تم الإلغاء (طرفين)",
CANCELLED: "ملغى",
RELEASED: "تم التحرير",
Reservation_notification: "اكتمل الحجز!",
Admin_notification: "حجز جديد!",
showQrcode: "رمز الحجز",
Status: "الحالة:",
Reserved1: "تم الحجز",
Occupied1: "✨تم تسجيل الحضور",
Cancelled: "ملغى",
Released1: "تم التحرير",
Called_Off: "تم الإلغاء (طرفين)",
Offer_selected: "العرض الترويجي:",
No_offers: "لا يوجد عرض",
Cost_with_colon: "التكلفة:",
Discount_with_colon: "نسبة الخصم %:",
SHARE: "مشاركة",
EXIT: "خروج",
cancel_booking: "هل ترغبين في إلغاء هذا الحجز؟",
cancel_booking2: "لا يمكنكِ إلغاء حجز مكتمل",
Cancel_notification: "تم إلغاء الحجز!",
Cancel_notification2: "تم إلغاء الحجز!",
NOTIFICATION1: "التنبيهات",
No_notification: "لا توجد تنبيهات!",
RESERVATION: "الحجز",
LOCKED: "مقفل",
NO_SHOW: "لم يحضر",
CLICK_TO_SCAN_RESERVATION_CODE: "مسح رمز الحجز",
NO_RESERVATION_CODE_SCANNED: "لا يمكن مسح هذا الرمز!",
Fetching_data: "جاري جلب البيانات . . .",
RESERVATION_CODE_SCANNED: "تم مسح رمز الحجز!",
ALLOT_RESERVATION: "تخصيص الحجز",
RESERVATION_IS_ALLOTED: "تم تخصيص الحجز!",
Click_lock_or_release: "اضغط للقفل أو الإلغاء",
AVAILABLE: "متاح",
Cannot_lock_or_release: "لا يمكن قفل أو تحرير هذه الفترة!",
LOCK: "قفل",
RELEASE: "تحرير",
Qty_with_colon: "العدد:",
Locked1: "مقفل",
to: " إلى ",
NoShow: "لم يحضر",
Cancel_notification3: "تم إلغاء الحجز!",
Rate: "تقييم",
Rate_your_experience: "قيمي تجربتكِ",
Payment: "الدفع",
Quota: "الحصة",
Used: "المستخدم",
Pay: "دفع",
Reservations: "الحجوزات",
CONFIRM: "تأكيد",
Description_with_colon: "الوصف:",
Quota_added: "الحجوزات المضافة:",
Transaction_reference: "مرجع المعاملة:",
Paid: "مدفوع",
Pending: "قيد الانتظار",
Failed: "فاشل",
Design: "تصميم",
Morning: "صباحاً",
Evening: "مساءً",
Language: "اللغة",
Software: "برمجيات",
Consultation: "استشارة",
Scan1: "مسح",
Test: "اختبار",
Purchase: "شراء",
Staff: "عضو الفريق",
Slot: "فترة",
No_payment_data_available: "عذراً! لا يوجد شيء هنا.",
Slot_Available: "فترة متاحة",
and: "و",
ALL: "الكل",
blank: "لا يمكن تركه فارغاً",
invalid: "البيانات غير مكتملة",
minmaxpassword: "يجب أن يتكون من ١٠ إلى ٣٦ حرفاً تشمل حروفاً صغيرة وكبيرة وأرقاماً ورموزاً خاصة",
mismatch: "يجب أن يتطابق مع كلمة المرور",
inuseemail: "📧بريد التواصل",
unverified: "البريد الإلكتروني غير مفعل",
incorrect: "البريد أو كلمة المرور غير صحيحة",
unregistered: "البريد الإلكتروني غير مسجل",
minmaxphone: "يجب أن يتكون من ٦ إلى ١٦ رقماً",
inusebname: "اسم المعرض هذا مستخدم من قبل شخص آخر",
selectstartdate: "اختر التاريخ",
selectenddate: "اختر التاريخ",
agentemail: "لا يمكن أن يكون بريد الوكيل والمسؤول هو نفسه",
uploadlogo: "يرجى تحميل شعار المعرض",
uploadimage: "يرجى تحميل صورة واحدة على الأقل",
slottimeless: "وقت البدء يجب أن يكون قبل وقت الانتهاء",
slottimeequal: "لا يمكن أن يكون وقت البدء والانتهاء متطابقين",
duplicate: "البيانات موجودة بالفعل",
itemname: "اختر خياراً واحداً على الأقل هنا",
minmaxcount: "يجب أن يكون أقل من ١٠٠,٠٠٠",
numonly: "لا يمكن استخدام أرقام عشرية",
countmore: "لا يمكن أن يكون ٠ أو أكبر من المتوفر",
limitmore: "لا يمكن أن يكون ٠ أو أكبر من المتوفر",
Select_one: "اختر خياراً واحداً على الأقل هنا",
numdeconly: "يجب أن يكون رقماً بعلامتين عشريتين",
minmaxcost: "يجب أن يكون أقل من ١٠٠,٠٠٠",
minmaxdiscount: "يجب أن يكون بين ٠ و ١٠٠",
selecttemplate: "اختر صورة إعلانية",
requestcancelled: "ألغى المستخدم الطلب",
signincancelled: "تم إلغاء عملية تسجيل الدخول",
backpressed: "تم الضغط على زر العودة",
Outlet: "منفذ بيع",
Store: "متجر",
Shop: "محل",
Fashion: "أزياء",
Shopping: "تسوق",
Item: "قطعة / عنصر",
Shopping_time: "وقت التسوق",
availabilitychanged: "قام شخص آخر بحجز اختياركِ.\nقد يكون حجزكِ غير مكتمل.",
statuschanged: "تم تحديث حالة هذا الحجز بالفعل",
Online: "عبر الإنترنت",
Offline: "بدون اتصال (ميداني)",
Readymade: "جاهز",
Custommade: "تفصيل (حسب الطلب)",
Bulkorder: "طلب بالجملة",
Model: "موديل",
Group: "مجموعة",
Individual: "فردي",
Single: "منفرد",
Package: "باقة",
Call: "اتصال",
Agent: "وكيل",
App_is_under_maintenance: "التطبيق قيد الصيانة. حاول لاحقاً",
UPDATE: "تحديث",
versionavailable: "نسخة جديدة من التطبيق متوفرة الآن!",
DOWNLOAD: "تحميل",
CART1: "السلة",
wrongimageformat: "يجب أن تكون الصورة بصيغة png أو jpeg",
Takeaway: "سفري",
Pickup: "استلام من الفرع",
CLEAR: "مسح / إزالة",
Select_your_address: "الموقع",
No_address_selected: "غير متاح",
Default: "عادي",
Free_text: "تعليق إضافي",
Address_selected: "الموقع",
Accessory: "إكسسوار",
Book2: "حجز",
businesses: "معارض",
CHANGE: "تغيير",
Minimum_Billing: "الحد الأدنى للفاتورة",
No_additional_comments: "لا توجد تعليقات إضافية",
Type_discount_or_Max_Discount_or_both: "حدد نسبة الخصم، أو حد الخصم، أو كليهما",
cannot_be_0: "اتركه فارغاً بدلاً من ٠",
discount_or_maxdiscount_is_required: "واحد على الأقل من هذه القيم إلزامي",
Must_be_greater_than_Max_discount: "يجب أن يكون أكبر من حد الخصم",
Release_offer: "ألغِ الحجوزات المرتبطة بهذا العرض ثم حاول مرة أخرى",
Active: "نشط",
Inactive: "غير نشط",
minbill_optional_for_discountonunit: "حدد تكلفة الوحدة أو الحد الأدنى للفاتورة",
minbill_mandatory_for_discountonbill: "الحد الأدنى للفاتورة إلزامي",
Minimum_Unitcost: "تكلفة الوحدة",
Select_eligibleunits: "اختر الوحدات المؤهلة",
promo_offer: "العرض فقط",
discount_on_unit: "خصم على وحدات محددة",
discount_on_bill: "خصم على إجمالي الفاتورة",
minucost_or_minbilling_is_allowed: "مطلوب قيمة واحدة فقط من هذه القيم",
Offer_minunitcost: "الحد الأدنى لتكلفة الوحدة",
Offer_minbill: "الحد الأدنى للفاتورة",
Cost: "التكلفة",
Usage_note5: "لم يُستخدم بعد",
You_will_pay: "ستدفعين",
Offer_on_unit: "خصم",
NotBooked: "غير محجوز",
Not_booked: "غير محجوز",
YOUR_ORDER: "طلبي",
Description: "الوصف",
Suite: "جناح",
Enter: "دخول",
Extend_bookings_close_date: "انتهت تواريخ الحجز. يرجى تمديد التاريخ.",
MANAGE_RESERVATION1: "الحجوزات / الطلبات",
Customer_pay: "سيتدفع الضيف",
Customer_save: "سيوفر الضيف",
Saved_Locations: "المواقع المحفوظة",
STATISTICS: "الإحصائيات",
VIEW_UNIT_BOOKING: "الحجوزات القائمة على الأعضاء",
BIRDS_EYE_VIEW: "عرض شامل",
ViewUnits_Intro_Message: "الحجوزات المسندة للفريق",
Scan_Intro_Message: "امسح رمز الحجز",
Birdseye_Intro_Message: "نظرة عامة على الحجوزات",
Statistics_Intro_Message: "أرقام ورسوم بيانية",
VIEW_FULL_BOOKING: "كل الحجوزات",
ViewFullBookings_Intro_Message: "قائمة بكافة الحجوزات",
UNITS: "الوحدات",
CUSTOMERS: "الضيوف",
Special_package: "باقة خاصة",
Sign_in_with_apple: "تسجيل الدخول بواسطة أبل",
Sign_up_with_apple: "إنشاء حساب بواسطة أبل",
Country: "الدولة",
City: "المدينة",
County: "محافظة",
District: "منطقة / حي",
pinzip: "الرمز البريدي",
Offer1: "عرض",
Report: "بلاغ / تقرير",
Agent_home: "رئيسية الوكيل",
Add_agent: "إضافة وكيل",
Update_agent: "تحديث معلومات الوكيل",
STAFF_VIEW: "عرض الفريق",
FULL_VIEW: "عرض كامل",
SCAN_NEW_CODE: "مسح رمز جديد",
BOOKING_DETAILS: "تفاصيل الحجز",
Do_you_want_to_calloff: "هل ترغبين في إلغاء هذا الحجز؟",
Billable_unit: "وحدة قابلة للفوترة",
Number_of_billable_units: "عدد الوحدات القابلة للفوترة",
Price_per_billable_unit: "السعر لكل وحدة قابلة للفوترة",
Reservation1: "الحجز",
Booking1: "الحجز",
Bookings: "الحجوزات",
BOOKING: "الحجز",
Business_data_retention: "ستظل بيانات المعرض في نظامنا لمدة ١٢ شهراً",
Item_update_timedelay: "ستطبق التغييرات خلال دقائق قليلة",
NOTVERIFIED: "غير موثق",
VERIFIED: "موثق",
Account_Created: "نشط من:",
Consumer: "ضيف",
SAVE: "حفظ",
No_website_found: "الموقع الإلكتروني غير متاح",
Home_Text1: "روائع التصاميم من نخبة المبدعين",
Home_Text2: "دخول سلس بأي حساب بريد إلكتروني",
Home_Text3: "سجل الدخول وابدأ الاستكشاف!",
Optometrist: "فحص نظر",
View_templates: "عرض الصور الإعلانية",
Templates: "الصور الإعلانية",
View_discount: "عرض العرض الترويجي",
Add_template: "إضافة صورة إعلانية",
Delete: "حذف",
Submit: "إرسال",
Edit_Country: "تحديث معلومات الدولة",
Connected_account: "الحساب المتصل",
Activate: "تفعيل",
Deactivate: "تعطيل",
Created_on: "أنشئ في",
Agent_registered: "الوكيل مسجل بالفعل",
Enter_email_alert: "أدخل البريد الإلكتروني",
Templatename_exist: "اسم الصورة الإعلانية موجود بالفعل",
Edit: "تعديل",
Country_exist: "الدولة موجودة بالفعل",
Add_country: "إضافة دولة",
Select_Country: "اختر الدولة",
Country_home: "رئيسية الدولة",
Scheme: "المخطط / النظام",
Banner: "صورة إعلانية",
Do_you_want_to_addcountry: "هل تريد إضافة الدولة؟",
Do_you_want_to_activate: "هل تريد التفعيل؟",
Do_you_want_to_deactivate: "هل تريد التعطيل؟",
Do_you_want_to_changecountry: "هل تريد تغيير الدولة؟",
numOrd: "العدد",
Logo_image: "الشعار",
Profile_picture: "صورة إعلانية",
Catalogue_image: "صورة الوحدة",
Add_segment: "إضافة مخطط",
Enter_Template: "اسم الصورة الإعلانية",
Edit_segment: "تحديث معلومات المخطط",
Video_call: "مكالمة فيديو",
Whatsapp_call: "مكالمة واتساب",
Zoom_call: "مكالمة زووم",
Googlemeet_call: "مكالمة جوجل ميت",
Teams_call: "مكالمة ميكروسوفت تيمز",
Banker: "مصرفي",
Organizer: "منظم",
Meetup: "لقاء",
Meet_at_a_location: "لقاء في موقع",
Interview: "مقابلة",
HelpSupport: "المساعدة والدعم",
EUR: "يورو",
INR: "روبية",
GBP: "جنيه إسترليني",
USD: "دولار",
Someone: "شخص ما",
My_upcoming_bookings: "حجوزاتي",
See_booking_history: "عرض جميع الحجوزات",
Add_more_favorites: "إضافة المزيد للمفضلة",
Add_favorites: "البحث في المعارض",
Search_distance: "مسافة البحث",
SEARCH: "بحث",
Import_contacts: "استيراد جهات الاتصال",
Add_customer: "إضافة ضيف",
MANAGE_CUSTOMER: "الضيوف",
No_business_favorites: "عذراً! لا يوجد شيء هنا.",
DELETE: "حذف",
Delete_question: "هل تريد حذف هذه المعلومات؟",
Customer_added: "تاريخ إضافة الضيف",
First_business_transaction: "أول تفاعل",
Last_business_transaction: "أحدث تفاعل",
Customer_list_empty: "عذراً! لا يوجد شيء هنا.",
Manage_Cust_Heading: "قائمة الضيوف",
OR_Import_contacts: "استيراد من جهات الاتصال",
Add_customer_manually: "أضف ضيفاً بالبريد، أو الهاتف، أو كليهما",
Lead_Time: "مدة التحضير",
minmaxleadtime: "يجب أن يكون بين ١ و ",
Status_by_lead_time: "خلال مدة التحضير، ستكون هذه القطعة:",
Days: "أيام",
Hours: "ساعات",
Minutes: "دقائق",
Delivered: "تم التوصيل",
Shipped: "تم الشحن",
Packed: "تم التغليف",
Prepared: "تم التجهيز",
Stock_Booking: "منتجات",
Slot_Booking: "خدمات",
Select_Stock_or_Slot: "اختر نوع المعرض",
Stock_Booking_Message: "سيكون لهذا المعرض كتالوج منتجات",
Slot_Booking_Message: "سيكون لهذا المعرض كتالوج خدمات",
Add_a_photo: "إضافة صورة",
Last_stock_updated_on: "التاريخ",
Last_stock_updated: "أحدث تحديث للمخزون",
Updated_by: "عضو الفريق",
Stock_available_now: "الكمية المتوفرة",
Add_stock: "إضافة كمية",
Remove_stock: "إزالة كمية",
OR: "أو",
Either_add_or_remove: "إما الإضافة أو الإزالة",
Remove_less_than_availability: "لا يمكن إزالة أكثر من المتوفر",
Count_0: "لا يمكن أن يكون ٠",
Select_working_days: "اختر أيام العمل",
Autoextend_enddate: "تمديد الفترة تلقائياً",
_1day: "يوم",
_2day: "يومين",
_7day: "٧ أيام",
_15day: "١٥ يوماً",
_30day: "٣٠ يوماً",
Booking_window: "طول فترة الحجز",
Order_limit_per_slot: "حد الطلبات",
Time_of_delivery: "التوصيل خلال",
Time_of_shipping: "الشحن خلال",
Time_of_packing: "التغليف خلال",
Time_of_preparation: "التجهيز خلال",
No_current_offername: " ",
No_current_offerdesc: " ",
Service_type_stock: "متى ستقوم بمعالجة الطلب؟",
SameDayService_Active: "خلال الفترة الزمنية التي اختارها الضيف",
SameDayService_Inactive: "خلال أي ساعة عمل ضمن مدة التحضير",
SameDayService_Instant: "خلال ساعة العمل التالية",
Instant: "فوري",
Available: "متاح",
Unavailable: "غير متاح",
Service_type_slot: "ماذا سيحصل الضيف في الفترة الزمنية المختارة؟",
Book_Person: "الوصول إلى شخص أو غرض فريد",
Book_Service: "الوصول إلى خدمة",
Person: "شخص",
Remove_from_favorites_question: "هل تريد مغادرة هذا المعرض؟",
Select_your_phone: "📞رقم هاتفكِ",
Select_your_email: "📧عنوان بريدكِ الإلكتروني",
Not_added_to_cart: "لا يمكن إضافة هذا للسلة",
Added_to_cart: "تمت الإضافة للسلة",
Delivery_slots_full: "لا توجد فترات متاحة",
DELIVER_SERVICES: "توصيل",
Delivery_View: "توصيل",
PREPARE_ORDER: "تجهيز (عرض-١)",
Prepare_View: "تجهيز",
OK: "موافق",
Do_you_want_to_update_question: "هل تريد الحفظ؟",
Prepare_Stock1_text: "- من قائمة الكتالوج -",
Select_a_delivery_date: "تاريخ التوصيل",
Prepare_Stock1: "تجهيز",
Delivery_Stock1: "توصيل",
Delivery_Stock1_text: "- من الطلبات الجاهزة -",
Load: "مفتوح",
Orders: "الطلبات",
Complete: "🏆مكتمل",
Order_ready: "جاهز",
Service_complete: "مكتمل",
Order_pending: "قيد الانتظار",
Select_applicable_days: "إلغاء اختيار الأيام غير المتاحة",
Min_1_Max: "يجب أن يكون بين ١ و ",
Prepare_Stock2: "تجهيز",
Delivery_Stock2: "توصيل",
Delivery_Stock2_text: "إكمال الطلب",
Prepare_Stock2_text: "تجهيز الطلب",
My_favorites: "مفضلاتي",
Booking_start: "تاريخ إنشاء المعرض",
Search_business: "ابحث عن جيفيجاليري",
Search: "بحث",
Contact: "التواصل",
Location: "الموقع",
Invites_you_to_its_new_adventure: "موجود في جيفيبوك!",
Invitation_mail_body: "اكتشفي عالماً من المزايا!",
Invitation_mail_body_share: "قومي بإجراء حجوزاتك أو طلباتك عبر تطبيق جيفيبوك.",
Regards: "شكراً لكِ،",
Added_you_to_its_community: "موجود في جيفيبوك!",
Added_favorites_mail_body: "أهلاً بكِ!<br><br>لقد تمت إضافتكِ إلى قائمة ضيوف هذا المعرض.<br><br>زوري المعرض في تطبيق جيفيبوك.",
Login_location: "الموقع",
Delete_message3: "هذا أمر محزن😢",
Delete_message4: "هل تريدين حقاً حذف حسابكِ؟ سيؤدي هذا إلى فصل معرف أبل الخاص بكِ عن جيفيبوك.\n لمعرفة البيانات التي سيتم حذفها، يرجى قراءة الشروط والسياسة.",
Contact_email: "📧بريد التواصل",
Import_contacts_do_you_want_to_popup: "هل تريد إضافة جهات الاتصال المختارة إلى قائمة الضيوف؟",
Ready: "جاهز",
READY: "جاهز",
Working_hours: "ساعات العمل",
Basic_2: "حسب استهلاكك",
GUEST_DETAILS: "تفاصيل الضيف",
GALLERY_DETAILS: "تفاصيل المعرض",
Phone_selected: "📞رقم الهاتف",
Email_selected: "📧البريد الإلكتروني",
COMPLETE: "🏆مكتمل",
COMPLETED: "🏆مكتمل",
Completed: "🏆مكتمل",
Bill: "الفاتورة",
NickName: "👤اللقب",
INFO: "معلومات",
IMAGES: "صور",
CUST_PAYMENT: "المدفوعات",
CONTACTS: "جهات الاتصال",
Manager: "مدير",
Owner: "مالك",
PayCard: "الدفع بالبطاقة",
Guest: "ضيف",
Service_time: "الفترة الزمنية للخدمة",
Service_location: "موقع الخدمة",
Women: "نساء",
Men: "رجال",
Handmade: "شغل يدوي",
Takeout: "سفري",
PayReceived: "تم استلام الدفعة",
Courier: "مندوب توصيل",
Product_delivery: "توصيل المنتج",
HomeDecor: "ديكور منزلي",
Guests: "الضيوف",
Unpaid: "الدفع قيد الانتظار",
Purchase_Order: "أمر شراء",
Appointment_Request: "طلب موعد",
Confirmed: "مؤكد",
Confirmed1: "مؤكد",
Custom_Product: "منتج حسب الطلب",
Decoration: "زينة / ديكور",
Visit_our_gallery: "زورينا في جيفيبوك.",
Digital_space_for_galleries_of_products_and_services: "مساحة رقمية لمعارض المنتجات والخدمات",
REFERENCE: "المرجع",
Max6: "الحد الأقصى: ٦ أحرف",
Reference: "المرجع",
Select_start_end_time: "اختر وقت البدء ووقت الانتهاء",
Cancelled_by_Consumer: "ألغيت من قبل الضيف",
Cancelled_by_Business: "ألغيت من قبل المعرض",
Basic_details: "التفاصيل الأساسية",
You_cannot_change_these_details_in_the_future: "لا يمكنكِ تغيير هذه التفاصيل مستقبلاً",
Rate_to_earn_rewards: "هل أعجبكِ هذا؟\nانقري هنا لتقييم تجربتكِ\n⭐✨🌟",
Delivery: "التوصيل",
Value_for_money: "القيمة مقابل السعر",
Quality: "الجودة",
Select_service: "اختيار الخدمة",
Applicable_on: "يطبق على",
Total_bill: "إجمالي مبلغ الفاتورة",
Full_Successful_booking_message: "تمت عملية الحجز بنجاح.",
Partial_Successful_booking_message: "يرجى الانتظار . . .",
Failed_booking_message: "عذراً، لم يكتمل الحجز بنجاح. حاولي مرة أخرى.",
Booking_details_are_in_the_home_or_email: "يمكنكِ العثور على التفاصيل في تبويب حجوزاتكِ، أو في بريدكِ الإلكتروني.",
Thank_you_for_the_order: "شكراً لكِ!",
Uh_oh: "عذراً!",
Conatct_Prominent_Disclosure_Heading: "الإفصاح عن البيانات التي يتم جمعها",
Business_Prominent_Disclosure_Heading: "يقوم جيفيبوك بجمع وتخزين بياناتكِ:\n\n👉 عنوان البريد الإلكتروني\n(لتسجيل الدخول والتواصل)\n\n👉 الموقع ورقم الهاتف\n(لتوصيل المنتج/الخدمة)\n\n👉 الوسائط\n(إذا اخترتِ نشرها)\n\n👉 جهات الاتصال\n(إذا اخترتِ دعوة الآخرين)",
Rating_successfully_done: "تم نشر تقييمكِ.\nشكراً لكِ!",
Communication_email: "📧بريد التواصل",
Workflow: "مسار العمل",
Verifcation_code: "رمز التحقق",
Cannot_be_rated: "لا يمكن تقييم هذا.",
Account_email: "📧بريد الحساب",
Clothing: "ملابس",
WORKFLOW: "مسار العمل",
Ontime: "في الوقت المحدد",
Closed: "مغلق",
CLOSED: "مغلق",
Share_email: "مشاركة البريد مع المعرض",
Shares_email: "مشاركة البريد مع الضيوف",
Share_email_phone: "مشاركة البريد ورقم الهاتف مع المعرض",
Shares_email_phone: "مشاركة البريد ورقم الهاتف مع الضيوف",
Share_email_phone_address: "مشاركة البريد ورقم الهاتف والعنوان مع المعرض",
Shares_email_phone_address: "مشاركة البريد ورقم الهاتف والعنوان مع الضيوف",
Share_email_address: "مشاركة البريد والعنوان مع المعرض",
Shares_email_address: "مشاركة البريد والعنوان مع الضيوف",
Share_phone_address: "مشاركة رقم الهاتف والعنوان مع المعرض",
Shares_phone_address: "مشاركة رقم الهاتف والعنوان مع الضيوف",
Share_email_phone_address_comment: "مشاركة البريد والهاتف والعنوان والملاحظات الإضافية مع المعرض",
Share_email_address_comment: "مشاركة البريد والعنوان والملاحظات الإضافية مع المعرض",
Share_phone_address_comment: "مشاركة الهاتف والعنوان والملاحظات الإضافية مع المعرض",
Share_address_comment: "مشاركة العنوان والملاحظات الإضافية مع المعرض",
Share_phone_comment: "مشاركة الهاتف والملاحظات الإضافية مع المعرض",
Share_email_comment: "مشاركة البريد والملاحظات الإضافية مع المعرض",
Share_phone: "مشاركة رقم الهاتف مع المعرض",
Shares_phone: "مشاركة رقم الهاتف مع الضيوف",
Share_address: "مشاركة العنوان مع المعرض",
Shares_address: "مشاركة العنوان مع الضيوف",
Share_comment: "مشاركة الملاحظات الإضافية مع المعرض",
New_arrivals_delivery_pickup: "وصول جديد - التوصيل والاستلام",
Order_clothing_from_catalog: "اطلب ملابس من الكتالوج",
Chat_with_gallery: "الدردشة مع المعرض",
Bookings_disabled: "الحجوزات معطلة",
Bookings_open_1day: "الحجوزات متاحة ليوم واحد",
Bookings_open_2days: "الحجوزات متاحة لمدة يومين",
Bookings_open_3days: "الحجوزات متاحة لمدة ٣ أيام",
Bookings_open_1week: "الحجوزات متاحة لأسبوع واحد",
Bookings_open_15days: "الحجوزات متاحة لمدة ١٥ يوماً",
Bookings_open_1month: "الحجوزات متاحة لشهر واحد",
Bookings_open_anytime: "الحجوزات متاحة في أي وقت",
booking_closed_by_gallery: "حجوزات المعرض مغلقة",
Dresses: "فساتين",
Abaya: "عباءة",
Burqa: "برقع",
Hijab: "حجاب",
ratings: "تقييمات",
Click_to_accept: "انقري هنا للقبول",
Use_rewards: "استخدام جيفيجولد",
Jiffyrewards: "جيفيجولد:",
Balance: "الرصيد:",
Level: "المستوى:",
Jiffyrewards1: "جيفيجولد",
ServiceCost: "تكلفة الخدمة",
Cost2: "التكلفة شاملة الضرائب",
Select_item_size: "الأنواع المتوفرة",
No_match_found: "غير موجود",
Admin1: "مسؤول",
PREPARE_ITEMVIEW: "تجهيز\nعرض العناصر",
PREPARE_ORDERVIEW: "تجهيز\nعرض الطلبات",
Select_item_length: "الخيارات المتاحة",
Select_item_material: "الخيارات المتاحة",
Select_custom_category: "الخيارات المتاحة",
Swipe_for_more: "مرري واختاري",
Select_labels: "اختيار الخصائص إلزامي",
Manage: "إدارة",
Filter: "تصفية",
Refresh: "تحديث",
Cart: "السلة",
JIFFYGALLERY_INVITATIONS: "دعوات جيفيجاليري",
ACCEPT_INVITATION: "قبول الدعوة",
Refer_Earn_Goldies_Per_Order: "ادعي الآخرين واكسبي جولد عن كل طلب يقومون به",
ReferralCode: "رمز الإحالة",
CouponCode: "رمز الكوبون",
Apply1: "تطبيق",
MoreInfo: "مزيد من المعلومات",
Select1: "اختر",
Self: "نفسي",
OtherDetails: "التحقق من التفاصيل الأخرى",
Join1: "انضمام",
MaxAllowedGoldies: "تم استخدامه في هذا الحجز:",
PREPARE_ORDER1: "تجهيز (عرض-٢)",
Prepare_Stock1_text1: "- من قائمة الطلبات -",
More: "المزيد",
Add_to_favorites_question: "إضافة هذا المعرض إلى المفضلة؟",
Added_to_favorites: "يمكنكِ الآن رؤية هذا المعرض في مفضلتكِ.",
Web: "الويب",
Finalize_order: "إتمام الطلب",
Save1: "حفظ",
Remove: "إزالة",
Selection: "اختيار",
Make_selection: "قومي باختياركِ",
Pick_variant: "اختاري النوع",
Pick_label: "اختاري الخصائص",
Enter_Available: "أدخل التوفر",
Digital_space_for_galleries_of_genuine_brands: "مساحة رقمية لمعارض\nالماركات الأصلية",
Login_signup_terms_policy_disclaimer: "بتسجيل الدخول أو إنشاء حساب، فإنكِ تؤكدين موافقتكِ على أحدث شروط وسياسات جيفيبوك",
Create_account_email: "إنشاء حساب ببريدكِ الإلكتروني",
JiffyGallery_Manager: "مدير جيفيجاليري",
Day: "يوم",
Day_Days: "يوم / أيام",
Login_with_email: "الدخول بالبريد الإلكتروني",
ViewMyGoldies: "جولد",
Villa: "الفيلا",
Estate: "العزبة",
Castle: "القلعة",
Palace: "القصر",
Fortress: "الحصن",
Citadel: "السيتي ديل",
Kingdom: "المملكة",
VillaMember: "عضو الفيلا",
EstateMember: "عضو العزبة",
CastleMember: "عضو القلعة",
PalaceMember: "عضو القصر",
FortressMember: "عضو الحصن",
CitadelMember: "عضو السيتي ديل",
KingdomMember: "عضو المملكة",
Member: "عضو",
Member1: "عضو",
Soldout1: "نفد من المخزون",
Allgalleries: "معارض أخرى",
Add_a_video: "إضافة فيديو",
Add_photos: "إضافة صور",
Type_of_promotion: "نوع العرض",
Add_catalog1: "إضافة كتالوج",
Number_of_Sections: "عدد الأقسام",
Hide: "إخفاء",
Activate_catalog_question: "تفعيل هذا الكتالوج؟",
Show_catalog_question: "عرض هذا الكتالوج للضيوف؟",
Enable_catalog_order_question: "السماح للمستخدمين بالطلب من هذا الكتالوج؟",
Dashboard: "لوحة التحكم",
Catalog1: "الكتالوج",
Catalog_units: "وحدات الكتالوج",
Dress_color: "لون القماش",
Embroidery: "التطريز",
Embroidery_color: "لون التطريز",
Embroidery_type: "أفكار التصميم",
Position: "موقع التطريز",
Create_my_AiAbaya: "ابتكري عباءتك بالذكاء الاصطناعي",
Try_another_design: "تجربة تصميم آخر",
Start_over: "البدء من جديد",
Type: "النوع",
Size: "المقاس",
Sky_is_the_limit: "أعجبكِ التصميم؟ اطلبيه الآن، أو أضيفيه لقائمة الأمنيات لطلبه لاحقاً.",
Creating_my_Ai_Abaya: "جاري ابتكار عباءتك...",
Order_my_Ai_Abaya: "اطلبي عباءة الذكاء الاصطناعي الخاصة بكِ",
Try_4_more_design: "تجربة ٤ تصميمات إضافية",
Try_3_more_design: "تجربة ٣ تصميمات إضافية",
Try_2_more_design: "تجربة ٢ تصميمات إضافية",
Try_1_more_design: "تجربة ١ تصميمات إضافية",
No_more_designs: "لا توجد تصميمات أخرى",
You_have_exceeded_your_quota: "اطلبي من تصميماتكِ المحفوظة للبدء في الإنتاج.",
Waiting_time: "وقت الانتظار",
wishlist: "قائمة الأمنيات",
open_wishlist: "فتح قائمة الأمنيات",
Order_from_wishlist: "اطلبي من قائمة الأمنيات",
Remove_an_image_from_the_wishlist: "قائمة الأمنيات ممتلئة. احذفي قطعة للمتابعة.",
Already_added_to_wishlist: "هذا التصميم موجود بالفعل في الأمنيات!",
No_Wishlist: "عذراً! لا يوجد شيء هنا.",
Select_from_wishlist: "انقر للاختيار والطلب",
Try_again_colon: "حاولي مرة أخرى:",
Designs: "تصميم / تصميمات",
CustomAIBooking: "طلبات الذكاء الاصطناعي",
RegularBooking: "طلبات عادية",
Confim_Stock1: "تجهيز",
Confim_Stock1_text: "مرحلة التجهيز الداخلي",
Confim_Stock2: "توصيل",
Confim_Stock2_text: "مرحلة توصيل العميل",
CONFIM_ORDER: "التوصيلات",
Select_delivery_date: "جاري التجهيز للتوصيل",
out_of_delivery: "جاري التوصيل",
Open_catalog: "فتح الكتالوج",
Order_now: "اطلبي الآن!",
PREPARE_MyView: "تجهيز\n(عرضي الخاص)",
DELIVERY_MyView: "توصي\n (عرضي الخاص)",
PREPARE_MyView_text: "التجهيزات المسندة إليّ",
DELIVERY_MyView_text: "التوصيلات المسندة إليّ",
Assign_Location_question: "تعيين موقع لهذا المستخدم",
Location_name: "اسم الموقع",
Delivery_by: "التوصيل بواسطة:",
Archived: "مؤرشف",
Dossier: "مجموعة",
Order_this: "اطلبي هذا التصميم",
Ai_abaya: "عباءة الذكاء الاصطناعي",
Jewels_ai: "مجوهرات الذكاء الاصطناعي",
Doubleclickzoom_Swipedownclose: "انقري مرتين للتكبير ومرري للأسفل للإغلاق",
Add_to_Wishlist: "إضافة للأمنيات",
Added: "تمت الإضافة",
Create_my_AiDesign: "ابتكري تصميمكِ بالذكاء الاصطناعي",
TypeCost: "تكلفة النوع",
Order_my_Ai_Design: "اطلبي تصميمكِ بالذكاء الاصطناعي",
Open_detailed_view: "فتح عرض التفاصيل",
Snapshot: "لقطة سريعة",
Unit_bookings: "حجوزات الوحدة",
Create_Business: "إضافة جيفيجاليري",
View_Business_Dashboard: "عرض لوحة التحكم",
View: "عرض",
Number_of_Trial_Limit: "التصميمات التي يمكنكِ حفظها:",
Select_a_business: "اختاري المعرض",
DesignCost: "تكلفة التصميم",
Pick_a_scene: "اختاري المشهد",
Ai_Design_Cost: "تكلفة التصميم",
Total: "الإجمالي",
countdown_text: "نصمم لكِ حلمكِ خلال دقيقة، بشكل لم يسبق له مثيل!",
Create_my_AiOffer: "إنشاء عرض ترويجي بالذكاء الاصطناعي",
This_order_is_fulfilled_by: "يتم تنفيذ هذا الطلب بواسطة:",
Country_of_origin: "بلد المنشأ",
Warranty: "الضمان",
Importer: "المستورد",
Click_to_open_gallery_legal: "اضغطي لقراءة الشروط والسياسات",
I_agree_to_the_Privacy_Policy: "أوافق على سياسة خصوصية جيفيبوك",
I_agree_to_the_Terms_of_Service: "أوافق على شروط جيفيبوك",
User_this: "استخدمي هذا",
OrderID: "رقم الطلب:",
Enable_during_checkout: "تفعيل أثناء الدفع",
Enter_valid_format_3dec: "أدخل بالصيغة الصحيحة (١٢.٣٤٥)",
Enter_valid_format_2dec: "أدخل بالصيغة الصحيحة (١٢,٣٤)",
Discovery_feed: "علامات تجارية أحبها",
Ai_Generated: "مولد بالذكاء الاصطناعي",
Add_quotation: "أضف السعر للمتابعة",
Incentivised_rating: "هذا التقييم مدفوع/تحفيزي",
Added_to_wishlist: "تمت الإضافة لقائمة أمنياتكِ!",
Failed_to_download: "فشل التحميل. حاولي مرة أخرى",
Image_saved_succesfully: "تم حفظ الصورة بنجاح",
Keyword: "كلمة دلالية",
Legal: "قانوني",
General: "عام",
Business1: "أعمال",
Gallery: "جيفيجاليري",
Customize: "تخصيص",
Taxes: "الضرائب",
Settings: "الإعدادات",
Galleries: "المعارض",
Homedelivery: "توصيل للمنزل",
Create_my_own_design: "صممي بنفسك",
TRENDING: "الأكثر رواجاً⚡",
CatalogName16: "اسم الكتالوج",
CoverPhoto916: "صورة الغلاف (٩:١٦ رأسي)",
CatalogDescription32: "وصف الكتالوج",
};