export default {
   Reserve_the_right_choice: "Digitaalne ruum galeriidele.",
   Email: "E-Post",
   Password: "Salasõna",
   Confirm_Password: "Korrake Salasõna",
   Sign_Up: "REGISTREERU",
   Log_In: "LOGI SISSE",
   Click_on_the_verification_link_that_is_sent_to_your_registered_email_ID: "E-posti kinnitamiseks, klõpsa oma E-postis olevale lingile.",
   CLOSE: "SULGE",
   Forgot_Password: "Unustasid Salasõna?",
   Verify_Email: "KINNITA E-POST",
   Reset_Password: "LÄHTESTA SALASÕNA",
   Back: "TAGASI",
   Password_reset: "Salasõna lähtestamiseks, klõpsa oma E-postil olevale lingile.",
   Accept: "NÕUSTU",
   Decline: "KEELDU",
   jiffybooklegal: "EELMÄNG",
   JiffyBook: "JIFFYBOOK",
   LOCATION_SETUP: "SEADISTA OMA ASUKOHT",
   Search_your_location: "Otsi asukohta",
   SAVE_LOCATION: "Salvesta",
   PROFILE_SETUP: "LOO OMA PROFIIL",
   Title: "MA OLEN . . .",
   Ms: "Naine",
   Mr: "Mees",
   Mrs: "Proua",
   Name: "NIMI",
   Phone: "TELEFONI NUMBER",
   SAVE_PROFILE: "SALVESTA",
   DELETE_ACCOUNT: "KUSTUTA KONTO",
   Delete_message1: "See on südantlõhestav :(",
   Delete_message2: "Kas soovid tõesti oma konto kustutada? Kustutatava info kohta tutvu tingimuste ja privaatsuspoliitikaga.",
   Yes: "JAH",
   No: "EI",
   Change_admin: "Edasta oma galerii omandiõigus ja proovi uuesti",
   My_Location: "MINU ASUKOHT",
   Service: "Salong",
   Event: "Restoran",
   Venue: "Teenus",
   Space: "Sündmus",
   Support: "Arst",
   Training: "Haigla",
   Art: "Asukoht",
   Register_a_business: "Ruum",
   exit_message: "Tugi",
   Sure: "KONSULTANT",
   Notyet: "PARKLA",
   Home: "Vaba Aeg",
   Account: "Treening",
   Booking: "Kunst Ja Disain",
   Notification: "Loo Galerii",
   Business: "Kas soovid rakenduse sulgeda?",
   About_us: "Ikka!",
   Sign_out: "MITTE VEEL",
   Aboutus2: "Avaleht",
   Aboutus4: "Profiil",
   Aboutus5: "Broneering",
   Aboutus6: "Teavitus",
   Aboutus7: "Galerii",
   Aboutus8: "Info",
   Nobusiness: "Logi välja",
   Click_to_ADD: "!! Eemaldatud !!",
   BUSINESS_NAME: "InDreamer OÜ, Estonia",
   Opens_at: "!! Eemaldatud !!",
   Closes_at: "Vaade",
   Add_success: "Teenuse tingimused ja privaatsuspoliitika",
   ADD_BUSINESS: "KÜLASTA",
   Recommendation: "JiffyBooki Veeb",
   Note: "lisateabe saamiseks",
   Business_Segment: "OI EI! SIIN POLE MIDAGI.",
   Select: "Lisamise Jaoks Klõpsa + Ikoonile",
   Doctor: "Galerii Nimi (50 Tähemärki)",
   Hospital: "Avamisaeg",
   Consultant: "Sulgemisaeg",
   Parking: "Lisatud Edukalt!",
   Recreation: "!! Eemaldatud !!",
   Select_business_segment: "Lisa Galerii",
   Business_Category: "Lisa Koha Nimi, Et Teha See Unikaalseks.",
   Business_Sub_category: "Mitmekohilste Galeriide Jaoks, Loo Iga Asukoha Jaoks Galerii.",
   Reservation_Item: "SKEEM",
   Selected: "VALI",
   Next: "VALI",
   Start_Date: "KATEGOORIA 1 MÄRGEND",
   End_Date: "KATEGOORIA 2 MÄRGEND",
   Exclude_Holiday: "Kataloogi Märgend",
   Holiday_List: "Valitud",
   Agent_email: "JÄRGMINE",
   Optional: "BRONEERIMISAKNA ALGUS",
   Business_Admin: "BRONEERMISAKNA LÕPP",
   Business_Email: "Lisa puhkus",
   Business_Phone: "Puhkuste loend",
   Business_Logo_Image: "AGENDI E-POST",
   Business_Profile_Photos: "(VABATAHTLIK)",
   uploadphotos10: "AVALIKU ADMINISTRAATORI NIMI",
   Business_Location: "AVALIKU ADMINISTRAATORI E-POST",
   DONE: "AVALIKU ADMINISTRAATORI TELEFON",
   Register_popup1: "LOGO (parimate tulemuste saamiseks kasuta ruudukujulist pilti)",
   Register_popup2: "BÄNNERID (parimate tulemuste saamiseks kasuta ruudukujulist pilti)",
   Terms: "Limiit: 10 Pilti",
   CANCEL: "ASUKOHT",
   I_AGREE: "SALVESTA",
   BUSINESS_HOME: "GALERII LOOMINE-",
   RESERVATION_SLOT: "KAS NÕUSTUTE TINGIMUSTE JA PRIVAATSUSPOLIITIKAGA?",
   RESERVATION_ITEM: "TINGIUSED JA PRIVAATSUSPOLIITIKA",
   BUSINESS_OFFER: "TÜHISTA",
   BUSINESS_STAFF: "NÕUSTU",
   MANAGE_PAYMENT: "GALERII AVALEHT",
   MANAGE_RESERVATION: "AJAPIIRKONNAD",
   UPDATE_BUSINESS: "KATALOOG",
   Enddate_popup: "EDENDAMINE",
   Release_day: "MEESKOND",
   Do_you_want_to_update: "FINANTSANDMED",
   information: "BRONEERINGUD / TELLIMUSED",
   Update_success: "VÄRSKENDA GALERIID",
   Not_authorized_to_delete: "Te ei saa lõppkuupäeva tagasi liigutada.",
   Do_you_want_to_delete: "Tühistage selle päeva broneeringud ja proovige uuesti.",
   Delete_success: "Kas soovite uuendada",
   Release_business: "andmed?",
   BUSINESS_PROFILE: "Uuendamine Õnnestus!",
   Business_Description: "TEIL EI OLE LUBA, ET KUSTUTADA.",
   Business_Website: "KAS SOOVITE KUSTUTADA",
   profile: "EDUKALT KUSTUTATUD!",
   RESERVATION_SLOT1: "TÜHISTA SELLE GALERII BRONEERINGUD JA PROOVI UUESTI",
   No_reservation_slot_added: "PROFIIL",
   Start_Time: "GALERII KIRJELDUS",
   End_Time: "GALERII KODULEHT",
   ADD_RESERVATION_SLOT: "?",
   Slot_NAME: "AJAPIIRKONNAD",
   Do_you_want_to_add: "Oi ei! Siin pole midagi.",
   slot_information: "ALGUSAEG",
   UPDATE_RESERVATION_SLOT: "LÕPPAEG",
   Slot_cannot_be_deleted: "LISA AJAPIIRKOND",
   slot: "AJAPIIRKONNA ID",
   Release_slot: "Kas soovite lisada",
   No_reservation_item_added: "andmed?",
   Count_per_slot: "UUENDA AJAPIIRKONNA INFOT",
   Cost1: "SEDA EI SAA KUSTUTADA! VÄHEMALT ÜKS AJAPIIRKOND ON KOHUSTUSLIK.",
   ADD_RESERVATION_ITEM: "ANDMED?",
   Count_Available: "TÜHISTA SELLE AJAPIIRKONNA BRONEERINGUD JA PROOVI UUESTI.",
   Custom_Name: "OI EI! SIIN POLE MIDAGI. ENNE ÜKSUSE LISAMIST LISA VÄHEMALT ÜKS AJAPIIRKOND",
   Limit_Per_Booking: "TEENUSE KÄTTESAADAVUS",
   Item_Description: "HIND",
   Upload_photos5: "LISA ÜKSUS",
   Specific_time: "TOOTE KÄTTESAADAVUS",
   Specific_staff: "KOHANDATUD NIMI",
   Available_From: "PIIRANG BRONEERINGU KOHTA",
   Available_Till: "KIRJELDUS\NPIIRANG - 128 TÄHEMÄRKI",
   Exclude_Date: "PIIRANG: 5 PILTI",
   Excluded_Date: "AJAPIIRKONNAD",
   UPDATE_RESERVATION_ITEM: "MEESKOND",
   Release_item: "SAADAVAL ALATES",
   BUSINESS_STAFF1: "SAADAVAL KUNI",
   No_business_staff_added: "Lisa puhkus",
   Admin: "Puhkuste loend",
   Staff_Email: "Uuenda Üksuse Infot",
   Role: "TÜHISTA SELLE ÜKSUSE BRONEERINGUD JA PROOVI UUESTI",
   ADD_BUSINESS_STAFF: "MEESKOND",
   Email_not_registered: "Oi ei! Siin pole midagi.",
   Do_you_want_to_continue: "Administraator",
   UPDATE_BUSINESS_STAFF: "E-POST",
   Staff_message3: "ROLL",
   BUSINESS_OFFER1: "LISA LIIGE",
   No_business_offer_added: "Kasutajat selle e-posti aadressiga ei leitud",
   Offer_Name: "KAS SOOVID JÄTKATA",
   Discount: "Uuenda Liikme Infot",
   Max_Discount: "need andmed?",
   ADD_BUSINESS_OFFER: "EDENDAMINE",
   Offer_Description: "OI EI! SIIN POLE MIDAGI.",
   Expires_On: "TIITEL",
   Select_your_ad_template: "ALLAHINDLUS %",
   Publish_this_ad: "ALLAHINDLUSE LIMIIT",
   Preview: "Lisa Soodustus",
   UPDATE_BUSINESS_OFFER: "LOOSUNG",
   Offer: "AEGUSMISKUUPÄEV",
   No_location: "BÄNNER",
   No_selection: "Avalda avalehele",
   Miles: "Eelvaade",
   Reviews: "Uuenda Soodustuse Infot",
   Loading1: "Need Andmed?",
   Services: "Oi Ei! Siin Pole Midagi.",
   Events: "Oi Ei! Siin Pole Midagi.",
   Doctors: "Miilid",
   Hospitals: "Arvustused",
   Venues: "Laadimine . . .",
   Spaces: "Salongid",
   Supports: "Restoranid",
   Consultants: "Teenused",
   Trainings: "Sündmused",
   Arts: "Arstid",
   Loading2: "Haiglad",
   Booking_open: "ASUKOHAD",
   View_Profile: "Ruumid",
   RUSH: "TOESTUSED",
   BOOK: "KONSULTANDID",
   SOON: "PARKLAD",
   Today: "Vaba Aja Tegevused",
   Tomorrow: "Koolitused",
   Sunday: "Kunsti Ja Disaini Valdkonnad",
   Monday: "Võimalused Sinu Ümber",
   Tuesday: "Broneerimisakna Algus",
   Wednesday: "Ava Profiil",
   Thursday: "Kiirusta",
   Friday: "Broneeri",
   Saturday: "Varsti",
   Soldout: "TÄNA",
   No_slots_for_booking: "Homme",
   No_reservation: "Pühapäev",
   No_slots_available: "Esmaspäev",
   Click_to_navigate: "Teisipäev",
   No_profile_description: "Kolmapäev",
   Available_offers: "Neljapäev",
   No_offer_available: "Reede",
   Offer_discount: "Laupäev",
   Offer_maximum: "TÄIS",
   Book1: "Oi Ei! Siin Pole Midagi.",
   You_will_save: "Oi ei! Siin pole midagi.",
   Avail_Offers: "Oi ei! Siin pole midagi.",
   None: "Klõpsa\Nnavigeerimiseks",
   No_offer_selected: "Profiili kirjeldus puudub",
   MY_BOOKING: "EDENDAMINE",
   No_booking: "Reklaame pole",
   RESERVED: "ALLAHINDLUS %",
   OCCUPIED: "MAKSIMAALNE ALLAHINDLUS",
   CALLED_OFF1: "BRONEERI",
   CANCELLED: "SÄÄSTAD",
   RELEASED: "EDENDAMINE",
   Reservation_notification: "Puudub",
   Admin_notification: "Reklaam puudub",
   showQrcode: "MINU BRONEERING",
   Status: "Oi Ei! Siin Pole Midagi.",
   Reserved1: "Broneeritud",
   Occupied1: "REGISTREERITUD",
   Cancelled: "Tühistatud",
   Released1: "Tühistatud",
   Called_Off: "Vabastatud",
   Offer_selected: "Broneering On Lõpule Viidud!",
   No_offers: "Uus broneering!",
   Cost_with_colon: "Broneeringukood",
   Discount_with_colon: "!! Eemaldatud !!",
   SHARE: "OLEK:",
   EXIT: "BRONEERITUD",
   cancel_booking: "REGISTREERITUD",
   cancel_booking2: "TÜHISTATUD",
   Cancel_notification: "VABASTATUD",
   Cancel_notification2: "TÜHISTATUD",
   NOTIFICATION1: "SOODUSTUS:",
   No_notification: "Reklaam puudub",
   RESERVATION: "HIND:",
   LOCKED: "ALLAHINDLUS %:",
   NO_SHOW: "JAGA",
   CLICK_TO_SCAN_RESERVATION_CODE: "VÄLJU",
   NO_RESERVATION_CODE_SCANNED: "Kas soovid selle broneeringu tühistada?",
   Fetching_data: "Lõpetatud broneeringut ei saa tühistada",
   RESERVATION_CODE_SCANNED: "Broneering tühistatud!",
   ALLOT_RESERVATION: "BRONEERING TÜHISTATUD!",
   RESERVATION_IS_ALLOTED: "Teavitus",
   Click_lock_or_release: "Teavitus puudub!",
   AVAILABLE: "BRONEERING",
   Cannot_lock_or_release: "Lukustatud",
   LOCK: "EI ILMU",
   RELEASE: "SKANEERI BRONEERINGKOOD",
   Qty_with_colon: "Seda Koodi Ei Saa Skaneerida!",
   Locked1: "Andmete Hankimine . . .",
   to: "Broneerimiskood skaneeritud!",
   NoShow: "Jaota Broneering",
   Cancel_notification3: "Broneering on määratud!",
   Rate: "Klõpsa Lukusta Või Tühista Broneeringu Jaoks",
   Rate_your_experience: "SAADAVAL",
   Payment: "SEDA AJAPIIRKONDA EI SAA LUKUSTADA EGA VABASTADA!",
   Quota: "Lukusta",
   Used: "Vabasta",
   Pay: "Loetle:",
   Reservations: "!! Eemaldatud !!",
   CONFIRM: "LUKUSTATUD",
   Description_with_colon: "-",
   Quota_added: "EI ILMU",
   Transaction_reference: "Broneering tühistatud!",
   Paid: "Hinnang",
   Pending: "!! Eemaldatud !!",
   Failed: "Hinda Oma Kogemust",
   Design: "Makse",
   Morning: "Piirmäär",
   Evening: "Kasutatud",
   Language: "!! Eemaldatud !!",
   Software: "!! Eemaldatud !!",
   Consultation: "!! Eemaldatud !!",
   Scan1: "!! Eemaldatud !!",
   Test: "!! Eemaldatud !!",
   Purchase: "Maksa",
   Staff: "!! Eemaldatud !!",
   Slot: "!! Eemaldatud !!",
   No_payment_data_available: "BRONEERINGUD",
   Slot_Available: "Luba Rakendusel Edasi Minna Maksega Ohutu Ja Edukaks Maksete Töötlemiseks Kasutab Rakendus Stripe, Mis Võib Koguda Sinu Andmeid, Sealhulgas Nime, Telefoninumbrit, E-Posti Aadressi, Asukohta, Pangaandmeid Ja Kaardiandmeid. Kui Jätkad Selle Maksega, Eeldame, Et Oled Nõus Selliste Andmete Jagamisega.",
   and: "KINNITA",
   ALL: "!! EEMALDATUD !!",
   blank: "Kirjeldus:",
   invalid: "!! Eemaldatud !!",
   minmaxpassword: "Krediteeritud broneeringud:",
   mismatch: "Tehingute viide:",
   inuseemail: "Makstud",
   unverified: "Ootel",
   incorrect: "Ebaõnnestus",
   unregistered: "!! Eemaldatud !!",
   minmaxphone: "Autod",
   inusebname: "Kinnisvara",
   selectstartdate: "Õigus",
   selectenddate: "Reisimine / Viisa",
   agentemail: "Sündmuste organiseerimine",
   uploadlogo: "Infrastruktuur",
   uploadimage: "Reklaam",
   slottimeless: "Karjäär",
   slottimeequal: "Raamatupidamine / Maksud",
   duplicate: "Alustav ettevõte",
   itemname: "Äritegevuse laiendamine",
   minmaxcount: "Disain",
   numonly: "Tõlge",
   countmore: "Valitsus",
   limitmore: "Linna keskus",
   Select_one: "Kaubanduskeskus",
   numdeconly: "Rannikuala",
   minmaxcost: "Järveäärne",
   minmaxdiscount: "Jõeäärne",
   selecttemplate: "Maantee",
   requestcancelled: "Viie tärni hotell",
   signincancelled: "Nelja tärni hotell",
   backpressed: "Vabaõhtu",
   Outlet: "Äärelinn",
   Store: "Katusekorrus",
   Shop: "Tänav",
   Fashion: "Tasuta Parkimine",
   Shopping: "Ürituse Toitlustamine",
   Item: "Väljas",
   Shopping_time: "Teater",
   availabilitychanged: "Võistlus",
   statuschanged: "Täispäev",
   Online: "Täisöö",
   Offline: "Hommik ",
   Readymade: "Õhtu",
   Custommade: "Ainult naistele",
   Bulkorder: "Tasuta Toit / Joogid",
   Model: "Auhinnaga",
   Group: "Auto",
   Individual: "Paat",
   Single: "Seadmed",
   Package: "Jaht",
   Call: "Mootorratas",
   Agent: "Jalgratas",
   App_is_under_maintenance: "Veoauto",
   UPDATE: "BUSS",
   versionavailable: "Mikrobuss",
   DOWNLOAD: "ÜLDINE",
   CART1: "AJU",
   wrongimageformat: "SIlmad",
   Takeaway: "Kõrv-Nina-Kõri",
   Pickup: "Hambad-Igemed",
   CLEAR: "SUU-JA.LÕUALUU KIRURGIA",
   Select_your_address: "Süda",
   No_address_selected: "Veri",
   Default: "Kopsud-Hingamine",
   Free_text: "Rasedus",
   Address_selected: "Selg",
   Accessory: "Närvid",
   Book2: "Luud-Liigesed-Lihased",
   businesses: "Neerud",
   CHANGE: "SEEDIMINE-AINEVAHETUS",
   Minimum_Billing: "Nahk-Juuksed-Küüned",
   No_additional_comments: "Hormoonid",
   Type_discount_or_Max_Discount_or_both: "Allergia-Immuunsus",
   cannot_be_0: "Sugu-Aretus",
   discount_or_maxdiscount_is_required: "Vaagen",
   Must_be_greater_than_Max_discount: "Kuseelundkond",
   Release_offer: "Meele-Uni",
   Active: "Ayurveda",
   Inactive: "Homõopaatia",
   minbill_optional_for_discountonunit: "Akupunktuur",
   minbill_mandatory_for_discountonbill: "Naturopaatia",
   Minimum_Unitcost: "SEIKLUS",
   Select_eligibleunits: "TREENING JA JÕUSAAL",
   promo_offer: "Vormisolek",
   discount_on_unit: "Pallimängud",
   discount_on_bill: "Õhusport",
   minucost_or_minbilling_is_allowed: "Veespordialad",
   Offer_minunitcost: "Rannasport",
   Offer_minbill: "Mäesport",
   Cost: "Sõitmine",
   Usage_note5: "Võistluskunstid",
   You_will_pay: "Mängud",
   Offer_on_unit: "Meditatsioon",
   NotBooked: "AINULT NAISTELE",
   Not_booked: "Ainult meestele",
   YOUR_ORDER: "PRUUT",
   Description: "Peigmees",
   Suite: "Lapsed",
   Enter: "Unisex",
   Extend_bookings_close_date: "Erilised poed",
   MANAGE_RESERVATION1: "KODUVISIIT",
   Customer_pay: "Arvuti",
   Customer_save: "Tehniline",
   Saved_Locations: "Mittetehniline",
   STATISTICS: "KEEL",
   VIEW_UNIT_BOOKING: "TARKVARA",
   BIRDS_EYE_VIEW: "KOOL",
   ViewUnits_Intro_Message: "Kõrgkool",
   Scan_Intro_Message: "Meditsiiniline",
   Birdseye_Intro_Message: "Isiksus",
   Statistics_Intro_Message: "Kunst",
   VIEW_FULL_BOOKING: "KONVERENTS",
   ViewFullBookings_Intro_Message: "Koosolek",
   UNITS: "SEMINAR",
   CUSTOMERS: "PULM",
   Special_package: "SÜNNIPÄEV",
   Sign_in_with_apple: "Töötuba",
   Sign_up_with_apple: "Festival",
   Country: "Pidu",
   City: "Etendus",
   County: "Näitus",
   District: "Meeskonnatöö",
   pinzip: "PIKNIK",
   Offer1: "Kontorikülastus",
   Report: "Telefonikõne",
   Agent_home: "ONLINE KONSULTATSIOON",
   Add_agent: "TAIMETOITLANE",
   Update_agent: "MITTETAIMETOITLANE",
   STAFF_VIEW: "VEGAN",
   FULL_VIEW: "KOHVIK",
   SCAN_NEW_CODE: "BURGER / VÕILEIB",
   BOOKING_DETAILS: "MEREANNID",
   Do_you_want_to_calloff: "Buffee",
   Billable_unit: "Halal",
   Number_of_billable_units: "Kosher",
   Price_per_billable_unit: "Drive-in",
   Reservation1: "Hiline Hommikueine",
   Booking1: "Kohalik Toit",
   Bookings: "Globaalne",
   BOOKING: "FUSIOON",
   Business_data_retention: "Ameerika",
   Item_update_timedelay: "Araabia",
   NOTVERIFIED: "AUSTRAALIA",
   VERIFIED: "BALKAN",
   Account_Created: "Balti",
   Consumer: "Kanada",
   SAVE: "KARIIBI",
   No_website_found: "Kontinentaalne",
   Home_Text1: "Ida-Kesk-Euroopa",
   Home_Text2: "Gruusia",
   Home_Text3: "Vahemere",
   Optometrist: "Mehhiko",
   View_templates: "Nordic",
   Templates: "ORIENTAL",
   View_discount: "Vene",
   Add_template: "SKANDINAAVIA",
   Delete: "LÕUNA-AMEERIKA",
   Submit: "LÕUNA-AASIA",
   Edit_Country: "TEX-MEX",
   Connected_account: "Türgi",
   Activate: "LÄHIS-AASIA",
   Deactivate: "HARIDUSLIK",
   Created_on: "Sport",
   Agent_registered: "Konsert",
   Enter_email_alert: "Turniir",
   Templatename_exist: "Meelelahutus",
   Edit: "ÄRI",
   Country_exist: "Kunst",
   Add_country: "HOBI",
   Select_Country: "Siseruum",
   Country_home: "SADAMA KOHT",
   Scheme: "LAADIMISPUNKT",
   Banner: "PARKIMINE JA TEENINDUS",
   Do_you_want_to_addcountry: "Talvine kaitse",
   Do_you_want_to_activate: "Vihma kaitse",
   Do_you_want_to_deactivate: "Päikse kaitse",
   Do_you_want_to_changecountry: "Hoiustamine ja Hooldamine",
   numOrd: "KONSULTATSIOON",
   Logo_image: "SKANEERI",
   Profile_picture: "TEST",
   Catalogue_image: "SISSEPÄÄS",
   Add_segment: "TREENERIGA",
   Enter_Template: "ILMA TREENERITA",
   Edit_segment: "VÄLJAK",
   Video_call: "Laud",
   Whatsapp_call: "Giidiga ekskursioon",
   Zoom_call: "Iseseisev Ekskursioon",
   Googlemeet_call: "Põld",
   Teams_call: "Väljak",
   Banker: "Bassein",
   Organizer: "Jääväljak",
   Meetup: "Käigurada",
   Meet_at_a_location: "Saun",
   Interview: "Ilu Ja Stiil",
   HelpSupport: "Heaolu",
   EUR: "JUUKSED",
   INR: "PEA",
   GBP: "NAHK",
   USD: "NÄGU / KAEL",
   Someone: "Otsaesine",
   My_upcoming_bookings: "Kulm ",
   See_booking_history: "Ripse",
   Add_more_favorites: "Ülahuul",
   Add_favorites: "Habe / Vunts",
   Search_distance: "Huuled",
   SEARCH: "DEKOLTEE",
   Import_contacts: "Käed",
   Add_customer: "KAENLAALUSED",
   MANAGE_CUSTOMER: "RIND",
   No_business_favorites: "Selg",
   DELETE: "KÕHT",
   Delete_question: "Bikiinipiirkond",
   Customer_added: "Tagumik",
   First_business_transaction: "Reied",
   Last_business_transaction: "Alajalad",
   Customer_list_empty: "Terved jalad",
   Manage_Cust_Heading: "JALG",
   OR_Import_contacts: "Küüned",
   Add_customer_manually: "Terve keha",
   Lead_Time: "Klassiruumikoolitus",
   minmaxleadtime: "Veebikoolitus",
   Status_by_lead_time: "Praktika / õpipoisiõpe",
   Days: "Auditoorium",
   Hours: "Tuba",
   Minutes: "Saal",
   Delivered: "Kohvik / Restoran",
   Shipped: "Sisehoov",
   Packed: "Liivapõhi",
   Prepared: "Muru",
   Stock_Booking: "Parkimine Ja Teenindus",
   Slot_Booking: "Rand",
   Select_Stock_or_Slot: "Klubi",
   Stock_Booking_Message: "Maapiirkond",
   Slot_Booking_Message: "Maaliline",
   Add_a_photo: "Müügiesindaja",
   Last_stock_updated_on: "Advokaat",
   Last_stock_updated: "Maakler",
   Updated_by: "Arhitekt",
   Stock_available_now: "Ehitaja",
   Add_stock: "Insener",
   Remove_stock: "Ürituste korraldaja",
   OR: "RAAMATUPIDAJA",
   Either_add_or_remove: "Audiitor",
   Remove_less_than_availability: "Disainer",
   Count_0: "Intervjuuer",
   Select_working_days: "NÕUSTAJA",
   Autoextend_enddate: "Abiline",
   _1day: "Ametnik",
   _2day: "Ekspert",
   _7day: "Laud",
   _15day: "Toit",
   _30day: "Toitlustamine",
   Booking_window: "LAUD ÜHELE",
   Order_limit_per_slot: "LAUD KAHELE",
   Time_of_delivery: "Laud kolmele",
   Time_of_shipping: "Laud neljale",
   Time_of_packing: "Laud kaheksale",
   Time_of_preparation: "Laud peoks",
   No_current_offername: "PRIVAATNE RUUM",
   No_current_offerdesc: "ERI MENÜÜ",
   Service_type_stock: "Kook",
   SameDayService_Active: "Toitlustusteenus",
   SameDayService_Inactive: "Autoparkimine",
   SameDayService_Instant: "Jalgrattaparkimine",
   Instant: "Pilet",
   Available: "Täiskasvanute Pilet",
   Unavailable: "Lapse Pilet",
   Service_type_slot: "Paari pilet",
   Book_Person: "Pere pilet",
   Book_Service: "Härrasmehe pilet",
   Person: "Daami Pilet",
   Remove_from_favorites_question: "Seltskonna pilet",
   Select_your_phone: "Standardpilet",
   Select_your_email: "Eripilet",
   Not_added_to_cart: "VIP-pilet",
   Added_to_cart: "Majandusklassi pilet",
   Delivery_slots_full: "Äriklassi pilet",
   DELIVER_SERVICES: "ESIMESE KLASSI PILET",
   Delivery_View: "KULDSE KLASSI PILET",
   PREPARE_ORDER: "Plaatina klassi pilet",
   Prepare_View: "TÖÖTAJA PILET",
   OK: "TASUTA PÄÄSE",
   Do_you_want_to_update_question: "Hoiustamine",
   Prepare_Stock1_text: "Paadi kinnitamine",
   Select_a_delivery_date: "Jahti kinnitamine",
   Prepare_Stock1: "MOOTORRATTA PARKIMINE",
   Delivery_Stock1: "JALGRATTA PARKIMINE",
   Delivery_Stock1_text: "Veoauto parkimine",
   Load: "Bussi Parkimine",
   Orders: "Mikrobussi Parkimine",
   Complete: "Auto Parkimine + Pesu",
   Order_ready: "Paadi Kinnitamine + Pesu",
   Service_complete: "Jahti Kinnitamine + Pesu",
   Order_pending: "Mootorratta Parkimine + Pesu",
   Select_applicable_days: "VEOAUTO PARKIMINE + PESU",
   Min_1_Max: "Bussi parkimine + pesu",
   Prepare_Stock2: "MIKROBUSSI PARKIMINE + PESU",
   Delivery_Stock2: "KIRURG",
   Delivery_Stock2_text: "Erialaarst",
   Prepare_Stock2_text: "Osakond",
   My_favorites: "Üldkirurg",
   Booking_start: "ÜLDARST (NAINE)",
   Search_business: "Üldarst (mees)",
   Search: "Südamekirurg",
   Contact: "SÜDAME-TORAKAALKIRURG",
   Location: "KOLOREKTAALKIRURG",
   Invites_you_to_its_new_adventure: "Dermatoloog (naine)",
   Invitation_mail_body: "Dermatoloog (mees)",
   Invitation_mail_body_share: "Endokriinkirurg",
   Regards: "Günekoloogiline Onkoloog (Naine)",
   Added_you_to_its_community: "Günekoloogiline onkoloog (mees)",
   Added_favorites_mail_body: "Neurokirurg",
   Login_location: "NEUROTOLOOG",
   Delete_message3: "Sünnitusabi/günekoloog (naine)",
   Delete_message4: "Sünnitusabi/günekoloog (mees)",
   Contact_email: "Oftalmoloog",
   Import_contacts_do_you_want_to_popup: "Suu-Lõualuu Kirurgia",
   Ready: "Ortodontist",
   READY: "OTROPEED",
   Working_hours: "Kõrva-nina-kurguarst",
   Basic_2: "Otoloog",
   GUEST_DETAILS: "PEDIAATRILINE KIRURG",
   GALLERY_DETAILS: "PLASTIKAKIRURG (NAINE)",
   Phone_selected: "Plastikakirurg (mees)",
   Email_selected: "Podiatrist",
   COMPLETE: "KOPSUARST",
   COMPLETED: "REPRODUKTIIVNENDOKRINOLOOG (NAINE)",
   Completed: "Reproduktiivnedokrinoloog (Mees)",
   Bill: "Reproduktiivkirurg (Naine)",
   NickName: "REPRODUKTIIVKIRURG (MEES)",
   INFO: "KIRURGILINE ONKOLOOG",
   IMAGES: "RINDKEREKIRURG",
   CUST_PAYMENT: "UROLOOG",
   CONTACTS: "VERESOONKIRURG",
   Manager: "Allergoloog-Immunoloog",
   Owner: "Anestesioloog",
   PayCard: "Kardioloog",
   Guest: "Hambaarst",
   Service_time: "Endokrinoloog",
   Service_location: "Gastroenteroloog",
   Women: "Geneetikaspetsialist",
   Men: "Geriaater",
   Handmade: "Günekoloog (Naine)",
   Takeout: "Günekoloog (Mees)",
   PayReceived: "Hematoloog",
   Courier: "Hospits- Ja Paliatiivmeditsiin",
   Product_delivery: "Nakkushaiguste Spetsialist",
   HomeDecor: "Internist",
   Guests: "Meditsiiniline Onkoloog",
   Unpaid: "Neeruarst",
   Purchase_Order: "Neuroloog",
   Appointment_Request: "Osteopaat",
   Confirmed: "Patoloog",
   Confirmed1: "PEDIAATER",
   Custom_Product: "Ennetava Meditsiini Spetsialist",
   Decoration: "Füsioterapeut",
   Visit_our_gallery: "Psühhiaater",
   Digital_space_for_galleries_of_products_and_services: "Kiiritusravi onkoloog",
   REFERENCE: "RADIOLOOG (NAINE)",
   Max6: "Radioloog (mees)",
   Reference: "Reumatoloog",
   Select_start_end_time: "Spordimeditsiini spetsialist",
   Cancelled_by_Consumer: "KT",
   Cancelled_by_Business: "EKG",
   Basic_details: "Eeg",
   You_cannot_change_these_details_in_the_future: "EMG",
   Rate_to_earn_rewards: "Endoskoop",
   Delivery: "Günekoloogiline Test (Naissoost Tehnik)",
   Value_for_money: "Günekoloogiline test (meessoost tehnik)",
   Quality: "Meg",
   Select_service: "MRI",
   Applicable_on: "EHO/KUULMINE",
   Total_bill: "PET",
   Full_Successful_booking_message: "Scintigraafia",
   Partial_Successful_booking_message: "SPECT",
   Failed_booking_message: "Tensilon",
   Booking_details_are_in_the_home_or_email: "Ultraheli",
   Thank_you_for_the_order: "Röntgen",
   Uh_oh: "Biopsia",
   Conatct_Prominent_Disclosure_Heading: "Luuüdi",
   Business_Prominent_Disclosure_Heading: "Maomahl",
   Rating_successfully_done: "Geneetiline",
   Communication_email: "GÜNEKOLOOGILINE SKANEERIMINE (NAISSOOST TEHNIK)",
   Workflow: "Günekoloogiline Skaneerimine (Meessoost Tehnik)",
   Verifcation_code: "Nimmepunktsioon",
   Cannot_be_rated: "Kopsufunktsioon",
   Account_email: "RASEDUSE DIAGNOOSIMINE",
   Clothing: "Sperma",
   WORKFLOW: "RÖGA",
   Ontime: "Väljaheide",
   Closed: "Torakentees",
   CLOSED: "URIIN",
   Share_email: "Erala",
   Shares_email: "Pooleraala",
   Share_email_phone: "Rühmatellimus",
   Shares_email_phone: "Individuaaltellimus",
   Share_email_phone_address: "Paketitellimus",
   Shares_email_phone_address: "Sulgpall",
   Share_email_address: "Banaanisõit",
   Shares_email_address: "Pesapall",
   Share_phone_address: "Korvpall",
   Shares_phone_address: "Kriket",
   Share_email_phone_address_comment: "Kurling",
   Share_email_address_comment: "Rahvastepall",
   Share_phone_address_comment: "Jalgpall",
   Share_address_comment: "Käsipall",
   Share_phone_comment: "Hokkii",
   Share_email_comment: "Iirimaa kurn",
   Share_phone: "Jäähoki",
   Shares_phone: "Lakross",
   Share_address: "Parvetamine",
   Shares_address: "Ragbi",
   Share_comment: "Jalgpall",
   New_arrivals_delivery_pickup: "Lauasõudmine (suur)",
   Order_clothing_from_catalog: "Squash",
   Chat_with_gallery: "Lauatennis",
   Bookings_disabled: "Tennis",
   Bookings_open_1day: "Võrkpall",
   Bookings_open_2days: "Veepolo",
   Bookings_open_3days: "Biljard",
   Bookings_open_1week: "Bowling",
   Bookings_open_15days: "Õhupüssimäng",
   Bookings_open_1month: "Ronimine",
   Bookings_open_anytime: "Akrobaatika",
   booking_closed_by_gallery: "Aeroobika",
   Dresses: "Aikido",
   Abaya: "Vibulaskmine",
   Burqa: "Kergejõustik",
   Hijab: "Paadisõit",
   ratings: "Kulturism",
   Click_to_accept: "Rada-alpinism",
   Use_rewards: "Poks",
   Jiffyrewards: "Jalgrattasõit",
   Balance: "Kettagolf",
   Level: "Driftisõit",
   Jiffyrewards1: "Sõitmine",
   ServiceCost: "Treening",
   Cost2: "Mõõgameisterlikkus",
   Select_item_size: "Lendlaud",
   No_match_found: "Liuglend",
   Admin1: "Golf",
   PREPARE_ITEMVIEW: "Võimlemine",
   PREPARE_ORDERVIEW: "Matkamine",
   Select_item_length: "Ratsutamine",
   Select_item_material: "Horseball",
   Select_custom_category: "Kuumaõhupalliga lendamine",
   Swipe_for_more: "Jetisõit",
   Select_labels: "Judo",
   Manage: "Karate",
   Filter: "Karting",
   Refresh: "Kanuusõit",
   Cart: "Kendo",
   JIFFYGALLERY_INVITATIONS: "KICKBOXING",
   ACCEPT_INVITATION: "LOHESURF",
   Refer_Earn_Goldies_Per_Order: "Kung Fu",
   ReferralCode: "Minigolf",
   CouponCode: "Mootorpaat",
   Apply1: "MUAY THAI",
   MoreInfo: "Öine Safari",
   Select1: "PAINTBALL",
   Self: "Langevarjuhüpped",
   OtherDetails: "Paraplaanilend",
   Join1: "PARASAILNING",
   MaxAllowedGoldies: "Petang",
   PREPARE_ORDER1: "Polo",
   Prepare_Stock1_text1: "Peobassein",
   More: "Võidusõit",
   Add_to_favorites_question: "Purjetamine",
   Added_to_favorites: "Privaatne saun",
   Web: "Ühiskasutatav Saun",
   Finalize_order: "Sukeldumine",
   Save1: "Laskmine",
   Remove: "Uisutamine",
   Selection: "Suusatamine",
   Make_selection: "Langevarjuhüpped",
   Pick_variant: "Snorgeldamine",
   Pick_label: "Suppamine",
   Enter_Available: "Surfamine",
   Digital_space_for_galleries_of_genuine_brands: "Ujumine",
   Login_signup_terms_policy_disclaimer: "Mõõgavõitlus",
   Create_account_email: "Wakeboarding",
   JiffyGallery_Manager: "Veesuusatamine",
   Day: "Tuulesurfamine",
   Day_Days: "Maadlus",
   Login_with_email: "Jooga",
   ViewMyGoldies: "Loomaia Tuur",
   Villa: "Veespordi Pakett",
   Estate: "Õhuspordi Pakett",
   Castle: "Mäespordi Pakett",
   Palace: "Rannaspordi Pakett",
   Fortress: "Stilist",
   Citadel: "Terapeut",
   Kingdom: "Sisepruunistus",
   VillaMember: "Juuksur (naine)",
   EstateMember: "Juuksur (mees)",
   CastleMember: "Jumestaja (naine)",
   PalaceMember: "Jumestaja (mees)",
   FortressMember: "Ripsmete/Kulmude tehnik (naine)",
   CitadelMember: "Ripsmete/Kulmude tehnik (mees)",
   KingdomMember: "Kosmeetik (naine)",
   Member: "Kosmeetik (Mees)",
   Member1: "Küünetehnik (naine)",
   Soldout1: "KÜÜNETEHNIK (MEES)",
   Allgalleries: "Henna disainer",
   Add_a_video: "Terapeut (naine)",
   Add_photos: "Terapeut (mees)",
   Type_of_promotion: "Massöör (naine)",
   Add_catalog1: "MASSÖÖR (MEES)",
   Number_of_Sections: "Päevitamise seanss",
   Hide: "Tehniline / Mittetehniline",
   Activate_catalog_question: "Kool / Kolledž",
   Show_catalog_question: "Toote tundmine",
   Enable_catalog_order_question: "Tarkvara programmeerimine",
   Dashboard: "Remont Ja Hooldus",
   Catalog1: "Tarkvaratööriista Õppimine",
   Catalog_units: "Äriarendus",
   Dress_color: "Ärijuhtimine",
   Embroidery: "Suhtlemine",
   Embroidery_color: "Klienditeenindus",
   Embroidery_type: "Andmeanalüüs",
   Position: "Juhtimine",
   Create_my_AiAbaya: "Fotograafia",
   Try_another_design: "Lugemine ja Kirjutamine",
   Start_over: "Õmblemine",
   Type: "Kirjutamine",
   Size: "Töö- Ja Eraelu Tasakaal",
   Sky_is_the_limit: "Töökoolitus",
   Creating_my_Ai_Abaya: "Esmaabi",
   Order_my_Ai_Abaya: "Õendus",
   Try_4_more_design: "Matemaatika",
   Try_3_more_design: "Ajalugu",
   Try_2_more_design: "Geograafia",
   Try_1_more_design: "Teadus",
   No_more_designs: "Füüsika",
   You_have_exceeded_your_quota: "Keemia",
   Waiting_time: "Bioloogia",
   wishlist: "Tehnoloogia",
   open_wishlist: "Arvutiõpetus",
   Order_from_wishlist: "Kaubandus",
   Remove_an_image_from_the_wishlist: "Haridus",
   Already_added_to_wishlist: "Kunst ja Humanitaarteadus",
   No_Wishlist: "Sotsiaalteadus",
   Select_from_wishlist: "Kirjandus",
   Try_again_colon: "Inseneriteadus",
   Designs: "Meditsiiniteadus",
   CustomAIBooking: "Raamatupidamine",
   RegularBooking: "Filosoofia",
   Confim_Stock1: "LOODUSTEADUS",
   Confim_Stock1_text: "Psühholoogia",
   Confim_Stock2: "ÕIGUSTEADUS",
   Confim_Stock2_text: "Avatud ala",
   CONFIM_ORDER: "SULETUD ALA",
   Select_delivery_date: "Avatud väljak",
   out_of_delivery: "Promenaad",
   Open_catalog: "Istekohad ja lauad",
   Order_now: "Lavastus, istekohad ja llauad",
   PREPARE_MyView: "Lava ja istekohad",
   DELIVERY_MyView: "Lava ja seisukohtade ala",
   PREPARE_MyView_text: "Ekraan ja seisukohtade ala",
   DELIVERY_MyView_text: "Mööbel",
   Assign_Location_question: "Elektroonika",
   Location_name: "Sõnum",
   Delivery_by: "Kohapeal söömine",
   Archived: "Seisukohtadel Publik",
   Dossier: "Tasuta Asjad",
   Order_this: "Istekohtadel publik",
   Ai_abaya: "Kirurgia",
   Jewels_ai: "Kardioloogia",
   Doubleclickzoom_Swipedownclose: "Dermatoloogia",
   Add_to_Wishlist: "Günekoloogia",
   Added: "Onkoloogia",
   Create_my_AiDesign: "Neuroloogia",
   TypeCost: "Neurotoloogia",
   Order_my_Ai_Design: "Sünnitusabi",
   Open_detailed_view: "Oftalmoloogia",
   Snapshot: "Ortodontia",
   Unit_bookings: "Ortopeedia",
   Create_Business: "OTORINOLARÜNGOLOOGIA",
   View_Business_Dashboard: "Otoloogia",
   View: "Pediaatria",
   Number_of_Trial_Limit: "Pulmonoloogia",
   Select_a_business: "Endokrinoloogia",
   DesignCost: "Uroloogia",
   Pick_a_scene: "Immunoloogia",
   Ai_Design_Cost: "Anestesioloogia",
   Total: "Hambaarst",
   countdown_text: "Gastroenteroloogia",
   Create_my_AiOffer: "Geneetika",
   This_order_is_fulfilled_by: "Geriaatria",
   Country_of_origin: "Hermatoloogia",
   Warranty: "Nakkushaigused",
   Importer: "Neeruhaigused",
   Click_to_open_gallery_legal: "Patoloogia",
   I_agree_to_the_Privacy_Policy: "Ennetav meditsiin",
   I_agree_to_the_Terms_of_Service: "Füsiatria",
   User_this: "Psühhiaatria",
   OrderID: "Radioloogia",
   Enable_during_checkout: "Reumatoloogia",
   Enter_valid_format_3dec: "Spordimeditsiini spetsialist",
   Enter_valid_format_2dec: "Unani",
   Discovery_feed: "SIDDHA",
   Ai_Generated: "Allopaatia",
   Add_quotation: "Mitu sihtkohta",
   Incentivised_rating: "Üks sihtkoht",
   Added_to_wishlist: "Kilomeetrite/miilide pakett",
   Failed_to_download: "Tunnipakett",
   Image_saved_succesfully: "Naised",
 };
