export default {
Reserve_the_right_choice: "Digitaalne ruum galeriidele",
Email: "📧E-Post",
Password: "🔑Parool",
Confirm_Password: "🔑Korda Parooli",
Sign_Up: "REGISTREERU",
Log_In: "LOGI SISSE",
Click_on_the_verification_link_that_is_sent_to_your_registered_email_ID: "E-posti kinnitamiseks klõpsake e-kirjas olevat linki",
CLOSE: "SULGE",
Forgot_Password: "Lähtesta Parool?",
Verify_Email: "KINNITA E-POST",
Reset_Password: "LÄHTESTA PAROOL",
Back: "TAGASI",
Password_reset: "Parooli lähtestamiseks\nklõpsake e-kirjas olevat linki",
Accept: "NÕUSTUN",
Decline: "KEELDUN",
jiffybooklegal: "TINGIMUSED JA REEGLID",
JiffyBook: "JIFFYBOOK",
LOCATION_SETUP: "MÄÄRA ASUKOHT",
Search_your_location: "Otsi asukohta",
SAVE_LOCATION: "Salvesta",
PROFILE_SETUP: "LOO MINU PROFIIL",
Title: "MINA OLEN . . .",
Ms: "Naine",
Mr: "Mees",
Mrs: "Proua",
Name: "👤NIMI",
Phone: "📞TELEFONINUMBER",
SAVE_PROFILE: "SALVESTA",
DELETE_ACCOUNT: "Kustuta konto",
Delete_message1: "See on kurb😢",
Delete_message2: "Kas soovid tõesti oma konto kustutada? Et lugeda, millised andmed kustutatakse, tutvu tingimuste ja eeskirjadega.",
Yes: "JAH",
No: "EI",
Change_admin: "Kanna galerii omandivorm üle ja proovi uuesti",
My_Location: "Minu asukoht",
Service: "Teenus",
Event: "Üritus",
Venue: "Toimumiskoht",
Space: "Ruum",
Support: "Tugi",
Training: "Koolitus",
Art: "Kunst",
Register_a_business: "Loo JiffyGallery",
exit_message: "Kas soovid rakenduse sulgeda?",
Sure: "MUIDUGI!",
Notyet: "VEEL MITTE",
Home: "Kodu",
Account: "Konto",
Booking: "Broneerimine",
Notification: "Teavitused",
Business: "JiffyGallery",
About_us: "Teave",
Sign_out: "Logi välja",
Aboutus2: "InDreamer OÜ, Eesti",
Aboutus4: "Vaata",
Aboutus5: "Kasutustingimused ja privaatsuspoliitika",
Aboutus6: "Külasta",
Aboutus7: "JiffyBooki veebisait",
Aboutus8: "lisateabe saamiseks",
Nobusiness: "Oih! Siin pole midagi.",
Click_to_ADD: "Lisa vajutades +",
BUSINESS_NAME: "GALERII NIMI (50 tähemärki)",
Opens_at: "Avamisaeg",
Closes_at: "Sulgemisaeg",
Add_success: "Edukalt lisatud!",
ADD_BUSINESS: "LISA JIFFYGALLERY",
Recommendation: "Lisa koha nimi, et see oleks unikaalne.",
Note: "Mitme asukohaga galeriide puhul loo galerii iga asukoha jaoks.",
Business_Segment: "SKEEM",
Select: "Vali",
Doctor: "Arst",
Hospital: "Haigla",
Consultant: "Konsultant",
Parking: "Parkimine",
Recreation: "Meelelahutus",
Select_business_segment: "Vali",
Business_Category: "Vali Kataloogid",
Business_Sub_category: "Vali Tellimuse Voog",
Reservation_Item: "KATALOOG",
Selected: "VALITUD",
Next: "EDASI",
Start_Date: "BRONEERIMISAKNA ALGUS",
End_Date: "BRONEERIMISAKNA LÕPP",
Exclude_Holiday: "Lisa Pühad",
Holiday_List: "Pühade Nimekiri",
Agent_email: "📧AGENDI E-POST",
Optional: "(VALIKULINE)",
Business_Admin: "👤Kontaktnimi",
Business_Email: "📧Kontakti e-post",
Business_Phone: "Kontakti telefon",
Business_Logo_Image: "LOGO (parima tulemuse saamiseks kasuta ruudukujulist pilti)",
Business_Profile_Photos: "BÄNNERID (parima tulemuse saamiseks kasuta ruudukujulisi pilte)",
uploadphotos10: "Piirang: 10 pilti",
Business_Location: "ASUKOHT",
DONE: "SALVESTA",
Register_popup1: "JiffyGallery loomine - ",
Register_popup2: "Kas nõustute tingimuste ja eeskirjadega?",
Terms: "Tingimused Ja Eeskirjad",
CANCEL: "TÜHISTA",
I_AGREE: "NÕUSTUN",
BUSINESS_HOME: "GALERII AVALEHT",
RESERVATION_SLOT: "AJAVAHEMIKUD",
RESERVATION_ITEM: "KATALOOG",
BUSINESS_OFFER: "KAMPAANIAD",
BUSINESS_STAFF: "MEESKOND",
MANAGE_PAYMENT: "FINANTSID",
MANAGE_RESERVATION: "BRONEERINGUD / TELLIMUSED",
UPDATE_BUSINESS: "UUENDA GALERIID",
Enddate_popup: "Lõppkuupäeva ei saa ajas tagasi nihutada",
Release_day: "Tühista selle päeva broneeringud ja proovi uuesti",
Do_you_want_to_update: "Kas soovid uuendada",
information: "andmeid?",
Update_success: "Edukalt uuendatud!",
Not_authorized_to_delete: "Teil puuduvad õigused kustutamiseks.",
Do_you_want_to_delete: "Kas soovid kustutada",
Delete_success: "Edukalt kustutatud!",
Release_business: "Tühista selle galerii broneeringud ja proovi uuesti",
BUSINESS_PROFILE: "Profiil",
Business_Description: "GALERII KIRJELDUS",
Business_Website: "GALERII VEEBISAIT",
profile: "?",
RESERVATION_SLOT1: "AJAVAHEMIK",
No_reservation_slot_added: "Oih! Siin pole midagi.",
Start_Time: "ALGUSAEG",
End_Time: "LÕPPAEG",
ADD_RESERVATION_SLOT: "LISA VAHEMIK",
Slot_NAME: "VAHEMIKU ID",
Do_you_want_to_add: "Kas soovid lisada",
slot_information: "andmeid?",
UPDATE_RESERVATION_SLOT: "UUENDA VAHEMIKU INFOT",
Slot_cannot_be_deleted: "Seda ei saa kustutada! Vähemalt üks vahemik on kohustuslik.",
slot: "andmeid?",
Release_slot: "Tühista selle vahemiku broneeringud ja proovi uuesti",
No_reservation_item_added: "Oih! Siin pole midagi. Enne üksuse lisamist lisa vähemalt üks ajavahemik",
Count_per_slot: "SAADAVUS",
Cost1: "MAKSUMUS",
ADD_RESERVATION_ITEM: "LISA ÜKSUS",
Count_Available: "SAADAVUS",
Custom_Name: "KOHANDATUD NIMI",
Limit_Per_Booking: "PIIRANG BRONEERINGU KOHTA",
Item_Description: "KIRJELDUS\nPiirang: 128 tähemärki",
Upload_photos5: "Piirang: 5 pilti",
Specific_time: "AJAVAHEMIKUD",
Specific_staff: "MEESKOND",
Available_From: "SAADAVAL ALATES",
Available_Till: "SAADAVAL KUNI",
Exclude_Date: "LISA PÜHAD",
Excluded_Date: "PÜHADE NIMEKIRI",
UPDATE_RESERVATION_ITEM: "UUENDA ÜKSUSE INFOT",
Release_item: "Tühista selle üksuse broneeringud ja proovi uuesti",
BUSINESS_STAFF1: "MEESKOND",
No_business_staff_added: "Oih! Siin pole midagi.",
Admin: "Peakasutaja",
Staff_Email: "📧E-Post",
Role: "ROLL",
ADD_BUSINESS_STAFF: "LISA LIIGE",
Email_not_registered: "Selle e-postiga kasutajat ei leitud",
Do_you_want_to_continue: "Kas soovid jätkata",
UPDATE_BUSINESS_STAFF: "UUENDA LIIKME INFOT",
Staff_message3: "neid andmeid?",
BUSINESS_OFFER1: "KAMPAANIAD",
No_business_offer_added: "Oih! Siin pole midagi.",
Offer_Name: "PEALKIRI",
Discount: "Soodustus %",
Max_Discount: "Soodustuse piirmäär",
ADD_BUSINESS_OFFER: "LISA KAMPAANIA",
Offer_Description: "SLOGAN",
Expires_On: "AEGUMISKUUPÄEV",
Select_your_ad_template: "BÄNNER",
Publish_this_ad: "Avalda klientidele",
Preview: "Eelvaade",
UPDATE_BUSINESS_OFFER: "UUENDA KAMPAANIA INFOT",
Offer: "neid andmeid?",
No_location: "Oih! Siin pole midagi.",
No_selection: "Oih! Siin pole midagi.",
Miles: " Miili",
Reviews: " Arvustust",
Loading1: "Laadimine . . . ",
Services: "Teenused",
Events: "Üritused",
Doctors: "Arstid",
Hospitals: "Haiglad",
Venues: "Toimumiskohad",
Spaces: "Ruumid",
Supports: "Tugi",
Consultants: "Konsultandid",
Trainings: "Koolitused",
Arts: "Kunst",
Loading2: "valikud sinu ümber",
Booking_open: "BRONEERIMISAKNA ALGUS",
View_Profile: "Ava profiil",
RUSH: "KIIRE",
BOOK: "BRONEERI",
SOON: "VARSTI",
Today: "Täna",
Tomorrow: "Homme",
Sunday: "Pühapäev",
Monday: "Esmaspäev",
Tuesday: "Teisipäev",
Wednesday: "Kolmapäev",
Thursday: "Neljapäev",
Friday: "Reede",
Saturday: "Laupäev",
Soldout: "TÄIS",
No_slots_for_booking: "Oih! Siin pole midagi.",
No_reservation: "🛒Sinu tellimused ilmuvad siia",
No_slots_available: "Oih! Siin pole midagi.",
Click_to_navigate: "Klõpsa\nnavigeerimiseks",
No_profile_description: "Profiili kirjeldus puudub",
Available_offers: "Vali pakkumine",
No_offer_available: "Kampaaniaid pole",
Offer_discount: "Soodustus %",
Offer_maximum: "Maksimaalne soodustus",
Book1: "Broneeri",
You_will_save: "Sinu sääst",
Avail_Offers: "Rakenda pakkumine",
None: "Puudub",
No_offer_selected: "Kampaaniat pole",
MY_BOOKING: "MINU BRONEERING",
No_booking: "Oih! Siin pole midagi.",
RESERVED: "BRONEERITUD",
OCCUPIED: "✨KOHAL",
CALLED_OFF1: "TÜHISTATUD (ÜHISELT)",
CANCELLED: "TÜHISTATUD",
RELEASED: "VABASTATUD",
Reservation_notification: "Broneering lõpetatud!",
Admin_notification: "Uus broneering!",
showQrcode: "Broneerimiskood",
Status: "Olek:",
Reserved1: "Broneeritud",
Occupied1: "✨KOHAL",
Cancelled: "Tühistatud",
Released1: "Vabastatud",
Called_Off: "Tühistatud (Ühiselt)",
Offer_selected: "Kampaania:",
No_offers: "Kampaaniat pole",
Cost_with_colon: "Maksumus:",
Discount_with_colon: "Soodustus %:",
SHARE: "JAGA",
EXIT: "VÄLJU",
cancel_booking: "Kas soovid selle broneeringu tühistada?",
cancel_booking2: "Lõpetatud broneeringut ei saa tühistada",
Cancel_notification: "Broneering tühistatud!",
Cancel_notification2: "Broneering tühistatud!",
NOTIFICATION1: "TEAVITUSED",
No_notification: "Teavitusi pole!",
RESERVATION: "BRONEERIMINE",
LOCKED: "LUKUSTATUD",
NO_SHOW: "EI ILMUNUD",
CLICK_TO_SCAN_RESERVATION_CODE: "SKÄNNI BRONEERIMISKOOD",
NO_RESERVATION_CODE_SCANNED: "Seda koodi ei saa skännida!",
Fetching_data: "Andmete hankimine . . .",
RESERVATION_CODE_SCANNED: "Broneerimiskood skännitud!",
ALLOT_RESERVATION: "MÄÄRA BRONEERING",
RESERVATION_IS_ALLOTED: "Broneering on määratud!",
Click_lock_or_release: "Klõpsa broneeringu LUKUSTAMISEKS või TÜHISTAMISEKS",
AVAILABLE: "SAADAVAL",
Cannot_lock_or_release: "Seda vahemikku ei saa lukustada ega vabastada!",
LOCK: "LUKUSTA",
RELEASE: "VABASTA",
Qty_with_colon: "Arv:",
Locked1: "Lukustatud",
to: " kuni ",
NoShow: "Ei Ilmunud",
Cancel_notification3: "Broneering tühistatud!",
Rate: "Hinda",
Rate_your_experience: "Hinda oma kogemust",
Payment: "MAKSE",
Quota: "Kvoot",
Used: "Kasutatud",
Pay: "Maksa",
Reservations: "Broneeringud",
CONFIRM: "KINNITA",
Description_with_colon: "Kirjeldus:",
Quota_added: "Broneeringud lisatud:",
Transaction_reference: "Tehingu viide:",
Paid: "Makstud",
Pending: "Ootel",
Failed: "Ebaõnnestunud",
Design: "Disain",
Morning: "Hommik",
Evening: "Õhtu",
Language: "Keel",
Software: "Tarkvara",
Consultation: "Konsultatsioon",
Scan1: "Skänni",
Test: "Test",
Purchase: "Ost",
Staff: "Meeskonnaliige",
Slot: "Vahemik",
No_payment_data_available: "Oih! Siin pole midagi.",
Slot_Available: "Vaba Ajavahemik",
and: "ja",
ALL: "KÕIK",
blank: "Ei tohi olla tühi",
invalid: "Andmed on puudulikud",
minmaxpassword: "Peab olema 10 kuni 36 tähemärki, sisaldama väikesi ja suuri tähti, numbreid ning erimärke",
mismatch: "Peab ühtima parooliga",
inuseemail: "📧Kontakti e-post",
unverified: "E-post on kinnitamata",
incorrect: "E-post või parool on vale",
unregistered: "E-posti pole registreeritud",
minmaxphone: "Peab olema 6 kuni 16 numbrit",
inusebname: "Keegi teine juba kasutab seda galerii nime",
selectstartdate: "Vali kuupäev",
selectenddate: "Vali kuupäev",
agentemail: "Agendi ja administraatori e-post ei saa olla sama",
uploadlogo: "Laadi üles galerii logo",
uploadimage: "Laadi üles vähemalt üks pilt",
slottimeless: "Algusaeg peab olema varasem kui lõpp-aeg",
slottimeequal: "Algus- ja lõpp-aeg ei saa olla samad",
duplicate: "Andmed on juba olemas",
itemname: "Vali siit vähemalt üks",
minmaxcount: "Peab olema väiksem kui 100 000",
numonly: "Ei tohi sisaldada komakohti",
countmore: "Ei saa olla 0 ega suurem kui saadavus",
limitmore: "Ei saa olla 0 ega suurem kui saadavus",
Select_one: "Vali siit vähemalt üks",
numdeconly: "Peab olema kahe komakohaga number",
minmaxcost: "Peab olema väiksem kui 100 000",
minmaxdiscount: "Peab olema vahemikus 0 kuni 100",
selecttemplate: "Vali bänner",
requestcancelled: "Kasutaja tühistas päringu",
signincancelled: "Sisselogimine tühistatud",
backpressed: "Vajutati tagasi-nuppu",
Outlet: "Väljund",
Store: "Kauplus",
Shop: "Pood",
Fashion: "Mood",
Shopping: "Ostlemine",
Item: "Üksus",
Shopping_time: "Ostlemise aeg",
availabilitychanged: "Keegi teine broneeris teie valiku.\nTeie broneering võib olla poolik.",
statuschanged: "Selle broneeringu olek on juba uuendatud",
Online: "Internetis",
Offline: "Võrguühenduseta",
Readymade: "Valmistoode",
Custommade: "Eritellimus",
Bulkorder: "Hulgitellimus",
Model: "Mudel",
Group: "Grupp",
Individual: "Üksikkasutaja",
Single: "Üksik",
Package: "Pakett",
Call: "Helista",
Agent: "Agent",
App_is_under_maintenance: "Rakendust hooldatakse. Proovi hiljem uuesti",
UPDATE: "UUENDA",
versionavailable: "Rakenduse uus versioon on saadaval!",
DOWNLOAD: "LAADI ALLA",
CART1: "OSTUKORV",
wrongimageformat: "Pilt peab olema .png või .jpeg vormingus",
Takeaway: "Kaasaost",
Pickup: "Tulen ise järele",
CLEAR: "TÜHJENDA",
Select_your_address: "Asukoht",
No_address_selected: "Pole saadaval",
Default: "Tavaline",
Free_text: "Lisakommentaar",
Address_selected: "Asukoht",
Accessory: "Lisatarvik",
Book2: "Broneeri",
businesses: "galeriid",
CHANGE: "MUUDA",
Minimum_Billing: "Miinimumarve",
No_additional_comments: "Lisakommentaare pole",
Type_discount_or_Max_Discount_or_both: "Määra soodustuse % või limiit või mõlemad",
cannot_be_0: "Jäta 0 asemel tühjaks",
discount_or_maxdiscount_is_required: "Vähemalt üks neist väärtustest on kohustuslik",
Must_be_greater_than_Max_discount: "Peab olema suurem kui soodustuse limiit",
Release_offer: "Tühista selle pakkumisega broneeringud ja proovi uuesti",
Active: "Aktiivne",
Inactive: "Mitteaktiivne",
minbill_optional_for_discountonunit: "Määra üksuse maksumus või miinimumarve",
minbill_mandatory_for_discountonbill: "Miinimumarve on kohustuslik",
Minimum_Unitcost: "ÜKSUSE MAKSUMUS",
Select_eligibleunits: "VALI SOBIVAD ÜKSUSED",
promo_offer: "Ainult kampaania",
discount_on_unit: "Soodustus valitud üksustele",
discount_on_bill: "Soodustus arve kogusummalt",
minucost_or_minbilling_is_allowed: "Nõutud on ainult üks neist väärtustest",
Offer_minunitcost: "Üksuse miinimummaksumus",
Offer_minbill: "Miinimumarve",
Cost: "Maksumus",
Usage_note5: "veel kasutamata",
You_will_pay: "Teie tasute",
Offer_on_unit: "Soodustus",
NotBooked: "BRONEERIMATA",
Not_booked: "BRONEERIMATA",
YOUR_ORDER: "MINU TELLIMUS",
Description: "Kirjeldus",
Suite: "Sviit",
Enter: "Sisene",
Extend_bookings_close_date: "Broneeringu kuupäevad on aegunud. Pikenda kuupäeva.",
MANAGE_RESERVATION1: "BRONEERINGUD / TELLIMUSED",
Customer_pay: "Külaline tasub",
Customer_save: "Külaline säästab",
Saved_Locations: "Salvestatud asukohad",
STATISTICS: "STATISTIKA",
VIEW_UNIT_BOOKING: "LIIKMEPÕHISED BRONEERINGUD",
BIRDS_EYE_VIEW: "ÜLDVAADE",
ViewUnits_Intro_Message: "Meeskonnale määratud broneeringud",
Scan_Intro_Message: "Skänni broneerimiskood",
Birdseye_Intro_Message: "Broneeringute ülevaade",
Statistics_Intro_Message: "Arvud Ja Graafikud",
VIEW_FULL_BOOKING: "KÕIK BRONEERINGUD",
ViewFullBookings_Intro_Message: "Kõikide broneeringute nimekiri",
UNITS: "ÜKSUSED",
CUSTOMERS: "KÜLALISED",
Special_package: "ERI-PAKETT",
Sign_in_with_apple: "Logi sisse Apple'iga",
Sign_up_with_apple: "Registreeru Apple'iga",
Country: "Riik",
City: "Linn",
County: "Maakond",
District: "Linnaosa",
pinzip: "POSTIINDEKS",
Offer1: "Pakkumine",
Report: "Raport",
Agent_home: "AGENDI AVALEHT",
Add_agent: "LISA AGENT",
Update_agent: "UUENDA AGENDI INFOT",
STAFF_VIEW: "MEESKONNA VAADE",
FULL_VIEW: "TÄISVAADE",
SCAN_NEW_CODE: "SKÄNNI UUS KOOD",
BOOKING_DETAILS: "BRONEERINGU ANDMED",
Do_you_want_to_calloff: "Kas soovid selle broneeringu tühistada?",
Billable_unit: "Arveldatav üksus",
Number_of_billable_units: "Arveldatavate üksuste arv",
Price_per_billable_unit: "Arveldatava üksuse hind",
Reservation1: "Broneerimine",
Booking1: "Broneerimine",
Bookings: "Broneeringud",
BOOKING: "BRONEERIMINE",
Business_data_retention: "Galerii andmed säilivad meie süsteemis 12 kuud",
Item_update_timedelay: "Muudatused rakenduvad mõne minuti jooksul",
NOTVERIFIED: "KINNITAMATA",
VERIFIED: "KINNITATUD",
Account_Created: "Aktiivne alates:",
Consumer: "Külaline",
SAVE: "SALVESTA",
No_website_found: "Veebisait pole saadaval",
Home_Text1: "Logi JiffyBooki sisse",
Home_Text2: "Logi sisse oma e-postiga",
Home_Text3: "Logi sisse, et avastada!",
Optometrist: "Optometrist",
View_templates: "Vaata bännereid",
Templates: "BÄNNERID",
View_discount: "Vaata kampaaniat",
Add_template: "LISA BÄNNER",
Delete: "KUSTUTA",
Submit: "ESITA",
Edit_Country: "UUENDA RIIGI INFOT",
Connected_account: "Seotud konto",
Activate: "AKTIVEERI",
Deactivate: "DEAKTIVEERI",
Created_on: "Loodud",
Agent_registered: "Agent on juba registreeritud",
Enter_email_alert: "Sisesta E-Post",
Templatename_exist: "Sellise nimega bänner on juba olemas",
Edit: "MUUDA",
Country_exist: "Riik on juba olemas",
Add_country: "LISA RIIK",
Select_Country: "Vali riik",
Country_home: "RIIGI AVALEHT",
Scheme: "SKEEM",
Banner: "BÄNNER",
Do_you_want_to_addcountry: "Kas soovid riiki lisada?",
Do_you_want_to_activate: "Kas soovid aktiveerida?",
Do_you_want_to_deactivate: "Kas soovid deaktiveerida?",
Do_you_want_to_changecountry: "Kas soovid riiki muuta?",
numOrd: "ARV",
Logo_image: "LOGO",
Profile_picture: "BÄNNER",
Catalogue_image: "ÜKSUSE PILT",
Add_segment: "LISA SKEEM",
Enter_Template: "BÄNNERI NIMI",
Edit_segment: "UUENDA SKEEMI INFOT",
Video_call: "Videokõne",
Whatsapp_call: "WhatsAppi kõne",
Zoom_call: "Zoomi Kõne",
Googlemeet_call: "Google Meeti Kõne",
Teams_call: "Microsoft Teamsi Kõne",
Banker: "Pankur",
Organizer: "Korraldaja",
Meetup: "Kokkusaamine",
Meet_at_a_location: "Kohtumine asukohas",
Interview: "Intervjuu",
HelpSupport: "Abi Ja Tugi",
EUR: "€",
INR: "₹",
GBP: "£",
USD: "$",
Someone: "Keegi",
My_upcoming_bookings: "Minu broneeringud",
See_booking_history: "Vaata kõiki broneeringuid",
Add_more_favorites: "Lisa veel lemmikuid",
Add_favorites: "Otsi galeriisid",
Search_distance: "Otsingu raadius",
SEARCH: "OTSI",
Import_contacts: "Impordi telefonikontaktid",
Add_customer: "LISA KÜLALINE",
MANAGE_CUSTOMER: "KÜLALISED",
No_business_favorites: "Oih! Siin pole midagi.",
DELETE: "KUSTUTA",
Delete_question: "Kas soovid need andmed kustutada?",
Customer_added: "Külalise lisamise kuupäev",
First_business_transaction: "Esimene suhtlus",
Last_business_transaction: "Viimane suhtlus",
Customer_list_empty: "Oih! Siin pole midagi.",
Manage_Cust_Heading: "KÜLALISTE NIMEKIRI",
OR_Import_contacts: "Impordi kontaktidest",
Add_customer_manually: "Lisa külaline e-posti, telefoninumbri või mõlemaga",
Lead_Time: "Ettevalmistusaeg",
minmaxleadtime: "See peab olema vahemikus 1 kuni ",
Status_by_lead_time: "Ettevalmistusaja jooksul see üksus:",
Days: "Päev(ad)",
Hours: "Tundi",
Minutes: "Minutit",
Delivered: "Tarnitud",
Shipped: "Saadetud",
Packed: "Pakitud",
Prepared: "Valmistatud",
Stock_Booking: "Tooted",
Slot_Booking: "Teenused",
Select_Stock_or_Slot: "Vali galerii tüüp",
Stock_Booking_Message: "Sellel galeriil on tootekataloog",
Slot_Booking_Message: "Sellel galeriil on teenustekataloog",
Add_a_photo: "Lisa foto",
Last_stock_updated_on: "Kuupäev",
Last_stock_updated: "Viimane laoseisu uuendus",
Updated_by: "Meeskonnaliige",
Stock_available_now: "Saadav kogus",
Add_stock: "Lisa kogus",
Remove_stock: "Eemalda kogus",
OR: "VÕI",
Either_add_or_remove: "Kas lisa või eemalda",
Remove_less_than_availability: "Ei saa eemaldada rohkem kui saadaval",
Count_0: "Ei saa olla 0",
Select_working_days: "VALI TÖÖPÄEVAD",
Autoextend_enddate: "Pikenda akent automaatselt",
_1day: "1 päev",
_2day: "2 päeva",
_7day: "7 päeva",
_15day: "15 päeva",
_30day: "30 päeva",
Booking_window: "BRONEERIMISAKNA PIKKUS",
Order_limit_per_slot: "TELLIMUSTE PIIRANG",
Time_of_delivery: "Tarne aeg:",
Time_of_shipping: "Saadetakse:",
Time_of_packing: "Pakitakse:",
Time_of_preparation: "Valmistatakse:",
No_current_offername: " ",
No_current_offerdesc: " ",
Service_type_stock: "Millal te tellimust töötlete?",
SameDayService_Active: "Külalise valitud ajavahemikus",
SameDayService_Inactive: "Suvalisel tööajal ettevalmistusaja jooksul",
SameDayService_Instant: "Järgmisel töötunnil",
Instant: "Kohene",
Available: "Saadaval",
Unavailable: "Pole Saadaval",
Service_type_slot: "Mida külaline valitud ajavahemikus saab?",
Book_Person: "Juurdepääsu isikule või unikaalsele esemele",
Book_Service: "Juurdepääsu teenusele",
Person: "Isik",
Remove_from_favorites_question: "Kas soovid sellest galeriist lahkuda?",
Select_your_phone: "📞Teie telefoninumber",
Select_your_email: "📧Teie e-posti aadress",
Not_added_to_cart: "Seda ei saa ostukorvi lisada",
Added_to_cart: "Lisatud ostukorvi",
Delivery_slots_full: "Vabu ajavahemikke pole",
DELIVER_SERVICES: "TARNI",
Delivery_View: "TARNI",
PREPARE_ORDER: "ETTEVALMISTUS (Vaade-1)",
Prepare_View: "ETTEVALMISTUS",
OK: "OK",
Do_you_want_to_update_question: "Kas soovid salvestada?",
Prepare_Stock1_text: "- kataloogi nimekirjast -",
Select_a_delivery_date: "Tarnekuupäev",
Prepare_Stock1: "ETTEVALMISTUS",
Delivery_Stock1: "TARNI",
Delivery_Stock1_text: "- valmis tellimuste hulgast -",
Load: "Avatud",
Orders: "Tellimused",
Complete: "🏆Lõpetatud",
Order_ready: "Valmis",
Service_complete: "Lõpetatud",
Order_pending: "Ootel",
Select_applicable_days: "TÜHISTA VALIK MITTESAADAVATEL PÄEVADEL",
Min_1_Max: "See peab olema vahemikus 1 kuni",
Prepare_Stock2: "ETTEVALMISTUS",
Delivery_Stock2: "TARNI",
Delivery_Stock2_text: "Lõpeta tellimus",
Prepare_Stock2_text: "Pane tellimus valmis",
My_favorites: "Minu lemmikud",
Booking_start: "GALERII LOOMISE KUUPÄEV",
Search_business: "Otsi JiffyGalleryt",
Search: "Otsi",
Contact: "KONTAKT",
Location: "ASUKOHT",
Invites_you_to_its_new_adventure: "on JiffyBookis!",
Invitation_mail_body: "Ava eelisõiguste maailm!",
Invitation_mail_body_share: "Tee oma broneeringud või tellimused JiffyBooki äpis.",
Regards: "Tänud,",
Added_you_to_its_community: "on JiffyBookis!",
Added_favorites_mail_body: "Tervist!<br><br>Te olete nüüd selle galerii külaliste nimekirjas.<br><br>Külastage galeriid JiffyBooki äpis.",
Login_location: "ASUKOHT",
Delete_message3: "See on kurb😢",
Delete_message4: "Kas soovid tõesti oma konto kustutada? See lahutab sinu Apple ID JiffyBookist.\n Et lugeda, millised andmed kustutatakse, tutvu tingimuste ja eeskirjadega.",
Contact_email: "📧Kontakti e-post",
Import_contacts_do_you_want_to_popup: "Kas soovid lisada valitud kontaktid külaliste nimekirja?",
Ready: "Valmis",
READY: "VALMIS",
Working_hours: "Tööajad",
Basic_2: "Kasutuse järgi",
GUEST_DETAILS: "KÜLALISE ANDMED",
GALLERY_DETAILS: "GALERII ANDMED",
Phone_selected: "📞TELEFONINUMBER",
Email_selected: "📧E-Post",
COMPLETE: "🏆LÕPETATUD",
COMPLETED: "🏆LÕPETATUD",
Completed: "🏆Lõpetatud",
Bill: "Arve",
NickName: "👤HÜÜDNIMI",
INFO: "INFO",
IMAGES: "PILDID",
CUST_PAYMENT: "MAKSED",
CONTACTS: "KONTAKTID",
Manager: "Juht",
Owner: "Omanik",
PayCard: "Maksa kaardiga",
Guest: "Külaline",
Service_time: "Teenuse ajavahemik",
Service_location: "Teenuse asukoht",
Women: "Naised",
Men: "Mehed",
Handmade: "Käsitöö",
Takeout: "Kaasaost",
PayReceived: "Makse Laekunud",
Courier: "Kuller",
Product_delivery: "Toote Tarne",
HomeDecor: "Kodusisustus",
Guests: "Külalised",
Unpaid: "Makse ootel",
Purchase_Order: "Ostutellimus",
Appointment_Request: "Kohtumise Päring",
Confirmed: "Kinnitatud",
Confirmed1: "KINNITATUD",
Custom_Product: "Eritellimustöö",
Decoration: "Dekoratsioon",
Visit_our_gallery: "Külastage meid JiffyBookis.",
Digital_space_for_galleries_of_products_and_services: "Digitaalne ruum toodete ja teenuste galeriidele",
REFERENCE: "VIIDE",
Max6: "Piirang: 6 tähemärki",
Reference: "Viide",
Select_start_end_time: "Vali algusaeg ja lõppaeg",
Cancelled_by_Consumer: "Külalise tühistatud",
Cancelled_by_Business: "Galerii tühistatud",
Basic_details: "Põhiandmed",
You_cannot_change_these_details_in_the_future: "Neid andmeid ei saa tulevikus muuta",
Rate_to_earn_rewards: "Kas see meeldis teile?\nKlõpsake siia, et hinnata oma kogemust\n⭐✨🌟",
Delivery: "Tarne",
Value_for_money: "Hinna ja kvaliteedi suhe",
Quality: "Kvaliteet",
Select_service: "Vali teenus",
Applicable_on: "Rakendatav:",
Total_bill: "Arve kogusumma",
Full_Successful_booking_message: "Broneerimine õnnestus.",
Partial_Successful_booking_message: "Palun oodake . . .",
Failed_booking_message: "Broneerimine ei õnnestunud. Proovi uuesti.",
Booking_details_are_in_the_home_or_email: "Andmed leiate broneeringute vahelehelt või oma e-postist.",
Thank_you_for_the_order: "Tänud!",
Uh_oh: "Oih!",
Conatct_Prominent_Disclosure_Heading: "Teave kogutavate andmete kohta",
Business_Prominent_Disclosure_Heading: "JiffyBook kogub ja salvestab teie:\n\n👉 E-posti aadressi\n(sisselogimiseks ja suhtluseks)\n\n👉 Asukoha ja telefoninumbri\n(toote/teenuse tarnimiseks)\n\n👉 Meediafailid\n(kui otsustate neid postitada)\n\n👉 Kontaktid\n(kui otsustate teisi kutsuda)",
Rating_successfully_done: "Teie hinnang on postitatud.\nTäname!",
Communication_email: "📧SUHTLUSE E-POST",
Workflow: "Töövoog",
Verifcation_code: "Kinnituskood",
Cannot_be_rated: "Seda ei saa hinnata.",
Account_email: "📧KONTO E-POST",
Clothing: "Rõivad",
WORKFLOW: "TÖÖVOOG",
Ontime: "Õigeaegselt",
Closed: "Suletud",
CLOSED: "SULETUD",
Share_email: "Jaga e-posti galeriiga",
Shares_email: "Jagab e-posti külalistega",
Share_email_phone: "Jaga e-posti ja telefoninumbrit galeriiga",
Shares_email_phone: "Jagab e-posti ja telefoninumbrit külalistega",
Share_email_phone_address: "Jaga e-posti, telefoninumbrit ja aadressi galeriiga",
Shares_email_phone_address: "Jagab e-posti, telefoninumbrit ja aadressi külalistega",
Share_email_address: "Jaga e-posti ja aadressi galeriiga",
Shares_email_address: "Jagab e-posti ja aadressi külalistega",
Share_phone_address: "Jaga telefoninumbrit ja aadressi galeriiga",
Shares_phone_address: "Jagab telefoninumbrit ja aadressi külalistega",
Share_email_phone_address_comment: "Jaga e-posti, telefoninumbrit, aadressi ja lisamärkmeid galeriiga",
Share_email_address_comment: "Jaga e-posti, aadressi ja lisamärkmeid galeriiga",
Share_phone_address_comment: "Jaga telefoninumbrit, aadressi ja lisamärkmeid galeriiga",
Share_address_comment: "Jaga aadressi ja lisamärkmeid galeriiga",
Share_phone_comment: "Jaga telefoninumbrit ja lisamärkmeid galeriiga",
Share_email_comment: "Jaga e-posti ja lisamärkmeid galeriiga",
Share_phone: "Jaga telefoninumbrit galeriiga",
Shares_phone: "Jagab telefoninumbrit külalistega",
Share_address: "Jaga aadressi galeriiga",
Shares_address: "Jagab aadressi külalistega",
Share_comment: "Jaga lisamärkmeid galeriiga",
New_arrivals_delivery_pickup: "Uued tooted - tarne ja järeletulemine",
Order_clothing_from_catalog: "Telli rõivaid kataloogist",
Chat_with_gallery: "Vestle galeriiga",
Bookings_disabled: "Broneerimine peatatud",
Bookings_open_1day: "Broneerimine avatud 1 päevaks",
Bookings_open_2days: "Broneerimine avatud 2 päevaks",
Bookings_open_3days: "Broneerimine avatud 3 päevaks",
Bookings_open_1week: "Broneerimine avatud 1 nädalaks",
Bookings_open_15days: "Broneerimine avatud 15 päevaks",
Bookings_open_1month: "Broneerimine avatud 1 kuuks",
Bookings_open_anytime: "Broneerimine avatud igal ajal",
booking_closed_by_gallery: "Galerii broneeringud on suletud",
Dresses: "Kleidid",
Abaya: "Abaya",
Burqa: "Burka",
Hijab: "Hüdžaab",
ratings: "arvustust",
Click_to_accept: "Klõpsa siia nõustumiseks",
Use_rewards: "Kasuta JiffyGoldisid",
Jiffyrewards: "JiffyGoldid:",
Balance: "Jääk:",
Level: "Tase:",
Jiffyrewards1: "JiffyGoldid",
ServiceCost: "Teenuse Maksumus",
Cost2: "Maksumus koos maksudega",
Select_item_size: "Saadaval variandid",
No_match_found: "Ei leitud",
Admin1: "Admin",
PREPARE_ITEMVIEW: "ETTEVALMISTUS\nÜKSUSE VAADE",
PREPARE_ORDERVIEW: "ETTEVALMISTUS\nTELLIMUSE VAADE",
Select_item_length: "Saadaval sildid",
Select_item_material: "Saadaval sildid",
Select_custom_category: "Saadaval sildid",
Swipe_for_more: "Tõmba ja vali",
Select_labels: "Sildi valik on kohustuslik",
Manage: "Halda",
Filter: "Filter",
Refresh: "Värskenda",
Cart: "Ostukorv",
JIFFYGALLERY_INVITATIONS: "JIFFYGALLERY KUTSED",
ACCEPT_INVITATION: "VÕTA KUTSE VASTU",
Refer_Earn_Goldies_Per_Order: "Soovita teistele ja teeni golde iga nende tehtud tellimuse pealt",
ReferralCode: "Soovituskood",
CouponCode: "Kupongikood",
Apply1: "RAKENDA",
MoreInfo: "Rohkem infot",
Select1: "VALI",
Self: "Ise",
OtherDetails: "Kontrolli muid andmeid",
Join1: "LIITU",
MaxAllowedGoldies: "Selles broneeringus kasutatud:",
PREPARE_ORDER1: "ETTEVALMISTUS (Vaade-2)",
Prepare_Stock1_text1: "- tellimuste nimekirjast -",
More: "Rohkem",
Add_to_favorites_question: "Kas lisada see galerii lemmikutesse?",
Added_to_favorites: "See galerii on nüüd teie lemmikute all.",
Web: "Veeb",
Finalize_order: "Lõpeta oma tellimus",
Save1: "Salvesta",
Remove: "Eemalda",
Selection: "Valik",
Make_selection: "Tehke oma valik",
Pick_variant: "Vali variant",
Pick_label: "Vali sildid",
Enter_Available: "Sisesta saadavus",
Digital_space_for_galleries_of_genuine_brands: "Digitaalne ruum\nehtsate brändide galeriidele",
Login_signup_terms_policy_disclaimer: "Sisselogimise või registreerumisega kinnitate, et nõustute JiffyBooki värskeimate tingimustega",
Create_account_email: "Loo konto oma e-postiga",
JiffyGallery_Manager: "JiffyGallery haldur",
Day: "Päev",
Day_Days: "Päev/Päeva",
Login_with_email: "Logi sisse e-postiga",
ViewMyGoldies: "Goldid",
Villa: "Villa",
Estate: "Mõis",
Castle: "Loss",
Palace: "Palee",
Fortress: "Kindlus",
Citadel: "Tsitadell",
Kingdom: "Kuningriik",
VillaMember: "Villa liige",
EstateMember: "Mõisa liige",
CastleMember: "Lossi liige",
PalaceMember: "Palee liige",
FortressMember: "Kindluse liige",
CitadelMember: "Tsitadelli liige",
KingdomMember: "Kuningriigi liige",
Member: "Liige",
Member1: "Liige",
Soldout1: "MÜÜDUD",
Allgalleries: "Teised galeriid",
Add_a_video: "Lisa video",
Add_photos: "Lisa fotod",
Type_of_promotion: "Kampaania tüüp",
Add_catalog1: "LISA KATALOOG",
Number_of_Sections: "Sektsioonide_arv",
Hide: "Peida",
Activate_catalog_question: "Kas aktiveerida see kataloog?",
Show_catalog_question: "Kas näidata seda kataloogi külalistele?",
Enable_catalog_order_question: "Kas lubada kasutajatel sellest kataloogist tellida?",
Dashboard: "Töölaud",
Catalog1: "Kataloog",
Catalog_units: "Kataloogi üksused",
Dress_color: "Kanga värv",
Embroidery: "Tikand",
Embroidery_color: "Tikandi värv",
Embroidery_type: "Disainiideed",
Position: "Tikandi asukoht",
Create_my_AiAbaya: "Loo minu AI Abaya",
Try_another_design: "Proovi teist disaini",
Start_over: "Alusta uuesti",
Type: "Tüüp",
Size: "Suurus",
Sky_is_the_limit: "Meeldib? Telli see meilt. Või lisa soovide nimekirja hilisemaks tellimiseks.",
Creating_my_Ai_Abaya: "Minu AI Abaya loomine ...",
Order_my_Ai_Abaya: "Telli minu AI Abaya",
Try_4_more_design: "Proovi veel 4 disaini",
Try_3_more_design: "Proovi veel 3 disaini",
Try_2_more_design: "Proovi veel 2 disaini",
Try_1_more_design: "Proovi veel 1 disaini",
No_more_designs: "Rohkem disaine pole",
You_have_exceeded_your_quota: "Esita tellimus oma mustanditest, et alustada tootmist.",
Waiting_time: "Ooteaeg",
wishlist: "Soovide Nimekiri",
open_wishlist: "Ava soovide nimekiri",
Order_from_wishlist: "Telli soovide nimekirjast",
Remove_an_image_from_the_wishlist: "Soovide nimekiri on täis. Lisa jätkamiseks eemalda mõni üksus.",
Already_added_to_wishlist: "See on juba soovide nimekirjas!",
No_Wishlist: "Oih! Siin pole midagi.",
Select_from_wishlist: "Vali ja keri tellimiseks alla",
Try_again_colon: "Proovi uuesti:",
Designs: "disain(id)",
CustomAIBooking: "Ai Tellimused",
RegularBooking: "Tavatellimused",
Confim_Stock1: "ETTEVALMISTUS",
Confim_Stock1_text: "Sisemine ettevalmistusetapp",
Confim_Stock2: "TARNI",
Confim_Stock2_text: "Kliendile tarnimise etapp",
CONFIM_ORDER: "TARNED",
Select_delivery_date: "Tarne ettevalmistamine",
out_of_delivery: "Toimub tarne",
Open_catalog: "Ava kataloog",
Order_now: "Telli kohe!",
PREPARE_MyView: "ETTEVALMISTUS\n(Minu vaade)",
DELIVERY_MyView: "TARNI\n(Minu vaade)",
PREPARE_MyView_text: "Mulle määratud ettevalmistused",
DELIVERY_MyView_text: "Mulle määratud tarned",
Assign_Location_question: "Määra sellele kasutajale asukoht",
Location_name: "Asukoha nimi",
Delivery_by: "Tarnija:",
Archived: "Arhiveeritud",
Dossier: "Kollektsioon",
Order_this: "Telli see",
Ai_abaya: "Ai Abaya",
Jewels_ai: "Jewels Ai",
Doubleclickzoom_Swipedownclose: "Suurendamiseks topeltklõps ja sulgemiseks tõmba alla",
Add_to_Wishlist: "Lisa soovide nimekirja",
Added: "Lisatud",
Create_my_AiDesign: "Loo minu AI disain",
TypeCost: "Tüübi Maksumus",
Order_my_Ai_Design: "Telli minu AI disain",
Open_detailed_view: "Ava üksikasjalik vaade",
Snapshot: "Kiirvaade",
Unit_bookings: "Üksuse broneeringud",
Create_Business: "LISA JIFFYGALLERY",
View_Business_Dashboard: "Vaata töölauda",
View: "Vaata",
Number_of_Trial_Limit: "Disainid, mida saad salvestada:",
Select_a_business: "Vali galerii",
DesignCost: "Disaini Maksumus",
Pick_a_scene: "Vali stseen",
Ai_Design_Cost: "Disaini Maksumus",
Total: "Kokku",
countdown_text: "Sinu unistuste disaini loomine vähem kui minutiga!\nNii nagu kunagi varem.",
Create_my_AiOffer: "Loo kampaania AI abil",
This_order_is_fulfilled_by: "Tellimust täidab:",
Country_of_origin: "Päritoluriik:",
Warranty: "Garantii:",
Importer: "Importija:",
Click_to_open_gallery_legal: "Klõpsake tingimuste ja reeglite lugemiseks",
I_agree_to_the_Privacy_Policy: "Nõustun JiffyBooki privaatsuspoliitikaga",
I_agree_to_the_Terms_of_Service: "Nõustun JiffyBooki tingimustega",
User_this: "Kasuta seda",
OrderID: "Tellimuse ID:",
Enable_during_checkout: "Luba kassas",
Enter_valid_format_3dec: "Sisesta korrektses vormingus (12.345)",
Enter_valid_format_2dec: "Sisesta korrektses vormingus (12.34)",
Discovery_feed: "BRÄNDID, MIDA ARMASTAN",
Ai_Generated: "AI-genereeritud",
Add_quotation: "Jätkamiseks lisa hind",
Incentivised_rating: "See on premeeritud hinnang",
Added_to_wishlist: "Lisatud teie soovide nimekirja!",
Failed_to_download: "Allalaadimine ebaõnnestus. Proovi uuesti",
Image_saved_succesfully: "Pilt edukalt salvestatud",
};