‎export default {
‎   Reserve_the_right_choice: "Digital space for galleries",
‎   Email: "📧Email",
‎   Password: "🔑Password",
‎   Confirm_Password: "🔑Repeat Password",
‎   Sign_Up: "SIGN UP",
‎   Log_In: "LOG IN",
‎   Click_on_the_verification_link_that_is_sent_to_your_registered_email_ID: "To verify email, click on the link in your email",
‎   CLOSE: "CLOSE",
‎   Forgot_Password: "Reset Password?",
‎   Verify_Email: "VERIFY EMAIL",
‎   Reset_Password: "RESET PASSWORD",
‎   Back: "BACK",
‎   Password_reset: "To reset password,\nclick on the link in your email",
‎   Accept: "ACCEPT",
‎   Decline: "DECLINE",
‎   jiffybooklegal: "TERMS & POLICIES",
‎   JiffyBook: "JIFFYBOOK",
‎   LOCATION_SETUP: "SET A LOCATION",
‎   Search_your_location: "Search location",
‎   SAVE_LOCATION: "Save",
‎   PROFILE_SETUP: "CREATE MY PROFILE",
‎   Title: "I AM . . .",
‎   Ms: "A woman",
‎   Mr: "A man",
‎   Mrs: "Mrs.",
‎   Name: "👤NAME",
‎   Phone: "📞PHONE NUMBER",
‎   SAVE_PROFILE: "SAVE",
‎   DELETE_ACCOUNT: "Delete account",
‎   Delete_message1: "This is heartbreaking😢",
‎   Delete_message2: "Do you really want to delete your account? To read what data will be deleted, read the Terms & Policy.",
‎   Yes: "YES",
‎   No: "NO",
‎   Change_admin: "Transfer your gallery ownership and try again",
‎   My_Location: "My location",
‎   Service: "Service",
‎   Event: "Event",
‎   Venue: "Venue",
‎   Space: "Space",
‎   Support: "Support",
‎   Training: "Training",
‎   Art: "Art",
‎   Register_a_business: "Create a JiffyGallery",
‎   exit_message: "Do you want to close the app?",
‎   Sure: "SURE!",
‎   Notyet: "NOT YET",
‎   Home: "Home",
‎   Account: "Account",
‎   Booking: "Booking",
‎   Notification: "Notification",
‎   Business: "JiffyGallery",
‎   About_us: "About",
‎   Sign_out: "Sign-out",
‎   Aboutus2: "InDreamer OÜ, Estonia",
‎   Aboutus4: "View",
‎   Aboutus5: "Terms of Service and Privacy Policy",
‎   Aboutus6: "Visit",
‎   Aboutus7: "JiffyBook Website",
‎   Aboutus8: "for more information",
‎   Nobusiness: "Uh-oh! There is nothing in here.",
‎   Click_to_ADD: "Click + to add",
‎   BUSINESS_NAME: "GALLERY NAME (50 characters)",
‎   Opens_at: "Opening hour",
‎   Closes_at: "Closing hour",
‎   Add_success: "Added successfully!",
‎   ADD_BUSINESS: "ADD JIFFYGALLERY",
‎   Recommendation: "Include place name to make it unique.",
‎   Note: "For multi-location galleries, create a gallery for each location.",
‎   Business_Segment: "SCHEMA",
‎   Select: "Select",
‎   Doctor: "Doctor",
‎   Hospital: "Hospital",
‎   Consultant: "Consultant",
‎   Parking: "Parking",
‎   Recreation: "Recreation",
‎   Select_business_segment: "Select",
‎   Business_Category: "Select Catalogs",
‎   Business_Sub_category: "Select Order Flow",
‎   Reservation_Item: "CATALOG",
‎   Selected: "SELECTED",
‎   Next: "NEXT",
‎   Start_Date: "BOOKING WINDOW START",
‎   End_Date: "BOOKING WINDOW END",
‎   Exclude_Holiday: "Add Holidays",
‎   Holiday_List: "Holiday List",
‎   Agent_email: "📧AGENT EMAIL",
‎   Optional: " (OPTIONAL)",
‎   Business_Admin: "👤Contact name",
‎   Business_Email: "📧Contact email",
‎   Business_Phone: "Contact phone",
‎   Business_Logo_Image: "LOGO (use square image for best results)",
‎   Business_Profile_Photos: "BANNERS (use square images for best results)",
‎   uploadphotos10: "Limit: 10 images",
‎   Business_Location: "LOCATION",
‎   DONE: "SAVE",
‎   Register_popup1: "Creating JiffyGallery - ",
‎   Register_popup2: "Do you accept the Terms & Policy?",
‎   Terms: "Terms & Policy",
‎   CANCEL: "CANCEL",
‎   I_AGREE: "ACCEPT",
‎   BUSINESS_HOME: "GALLERY HOME",
‎   RESERVATION_SLOT: "TIME-SLOTS",
‎   RESERVATION_ITEM: "CATALOG",
‎   BUSINESS_OFFER: "PROMOTIONS",
‎   BUSINESS_STAFF: "TEAM",
‎   MANAGE_PAYMENT: "FINANCIALS",
‎   MANAGE_RESERVATION: "BOOKINGS / ORDERS",
‎   UPDATE_BUSINESS: "UPDATE GALLERY",
‎   Enddate_popup: "You cannot move the end date backwards",
‎   Release_day: "Cancel the bookings of this day and then try again",
‎   Do_you_want_to_update: "Do you want to update",
‎   information: "data?",
‎   Update_success: "Updated successfully!",
‎   Not_authorized_to_delete: "You do not have the permission to delete.",
‎   Do_you_want_to_delete: "Do you want to delete",
‎   Delete_success: "Deleted successfully!",
‎   Release_business: "Cancel the bookings of this gallery and then try again",
‎   BUSINESS_PROFILE: "Profile",
‎   Business_Description: "GALLERY DESCRIPTION",
‎   Business_Website: "GALLERY WEBSITE",
‎   profile: "?",
‎   RESERVATION_SLOT1: "TIME-SLOT",
‎   No_reservation_slot_added: "Uh-oh! There is nothing in here.",
‎   Start_Time: "START TIME",
‎   End_Time: "END TIME",
‎   ADD_RESERVATION_SLOT: "ADD SLOT",
‎   Slot_NAME: "SLOT ID",
‎   Do_you_want_to_add: "Do you want to add",
‎   slot_information: "data?",
‎   UPDATE_RESERVATION_SLOT: "UPDATE SLOT INFO",
‎   Slot_cannot_be_deleted: "You cannot delete this! At least one slot is mandatory.",
‎   slot: "data?",
‎   Release_slot: "Cancel the bookings of this slot and then try again",
‎   No_reservation_item_added: "Uh-oh! There is nothing in here. Add at least one time slot before adding a unit",
‎   Count_per_slot: "AVAILABILITY",
‎   Cost1: "COST",
‎   ADD_RESERVATION_ITEM: "ADD UNIT",
‎   Count_Available: "AVAILABILITY",
‎   Custom_Name: "CUSTOM NAME",
‎   Limit_Per_Booking: "LIMIT PER BOOKING",
‎   Item_Description: "DESCRIPTION\nLimit: 128 characters",
‎   Upload_photos5: "Limit: 5 images",
‎   Specific_time: "TIME-SLOTS",
‎   Specific_staff: "TEAM",
‎   Available_From: "AVAILABLE FROM",
‎   Available_Till: "AVAILABLE UNTIL",
‎   Exclude_Date: "ADD HOLIDAYS",
‎   Excluded_Date: "HOLIDAY LIST",
‎   UPDATE_RESERVATION_ITEM: "UPDATE UNIT INFO",
‎   Release_item: "Cancel the bookings of this unit and then try again",
‎   BUSINESS_STAFF1: "TEAM",
‎   No_business_staff_added: "Uh-oh! There is nothing in here.",
‎   Admin: "SuperAdmin",
‎   Staff_Email: "📧Email",
‎   Role: "ROLE",
‎   ADD_BUSINESS_STAFF: "ADD MEMBER",
‎   Email_not_registered: "No user is found with email",
‎   Do_you_want_to_continue: "Do you want to continue",
‎   UPDATE_BUSINESS_STAFF: "UPDATE MEMBER INFO",
‎   Staff_message3: "this data?",
‎   BUSINESS_OFFER1: "PROMOTIONS",
‎   No_business_offer_added: "Uh-oh! There is nothing in here.",
‎   Offer_Name: "TITLE",
‎   Discount: "Discount %",
‎   Max_Discount: "Discount limit",
‎   ADD_BUSINESS_OFFER: "ADD PROMOTION",
‎   Offer_Description: "SLOGAN",
‎   Expires_On: "EXPIRY DATE",
‎   Select_your_ad_template: "BANNER",
‎   Publish_this_ad: "Publish to customers",
‎   Preview: "Preview",
‎   UPDATE_BUSINESS_OFFER: "UPDATE PROMOTION INFO",
‎   Offer: "this data?",
‎   No_location: "Uh-oh! There is nothing in here.",
‎   No_selection: "Uh-oh! There is nothing in here.",
‎   Miles: " Miles",
‎   Reviews: " Reviews",
‎   Loading1: "Loading . . . ",
‎   Services: "Services",
‎   Events: "Events",
‎   Doctors: "Doctors",
‎   Hospitals: "Hospitals",
‎   Venues: "Venues",
‎   Spaces: "Spaces",
‎   Supports: "Supports",
‎   Consultants: "Consultants",
‎   Trainings: "Trainings",
‎   Arts: "Arts",
‎   Loading2: "options around you",
‎   Booking_open: "BOOKING WINDOW START",
‎   View_Profile: "Open profile",
‎   RUSH: "RUSH",
‎   BOOK: "BOOK",
‎   SOON: "SOON",
‎   Today: "Today",
‎   Tomorrow: "Tomorrow",
‎   Sunday: "Sunday",
‎   Monday: "Monday",
‎   Tuesday: "Tuesday",
‎   Wednesday: "Wednesday",
‎   Thursday: "Thursday",
‎   Friday: "Friday",
‎   Saturday: "Saturday",
‎   Soldout: "FULL",
‎   No_slots_for_booking: "Uh-oh! There is nothing in here.",
‎   No_reservation: "🛒Your orders will appear here",
‎   No_slots_available: "Uh-oh! There is nothing in here.",
‎   Click_to_navigate: "Click to\nNavigate",
‎   No_profile_description: "No profile description",
‎   Available_offers: "Select offer",
‎   No_offer_available: "No promotions",
‎   Offer_discount: "Discount %",
‎   Offer_maximum: "Maximum discount",
‎   Book1: "Book",
‎   You_will_save: "You will save",
‎   Avail_Offers: "Apply an offer",
‎   None: "None",
‎   No_offer_selected: "No promotion",
‎   MY_BOOKING: "MY BOOKING",
‎   No_booking: "Uh-oh! There is nothing in here.",
‎   RESERVED: "BOOKED",
‎   OCCUPIED: "✨CHECKED-IN",
‎   CALLED_OFF1: "CALLED OFF",
‎   CANCELLED: "CANCELLED",
‎   RELEASED: "RELEASED",
‎   Reservation_notification: "Booking complete!",
‎   Admin_notification: "New booking!",
‎   showQrcode: "Booking code",
‎   Status: "Status:",
‎   Reserved1: "Booked",
‎   Occupied1: "✨Checked-in",
‎   Cancelled: "Cancelled",
‎   Released1: "Released",
‎   Called_Off: "Called Off",
‎   Offer_selected: "Promotion:",
‎   No_offers: "No promotion",
‎   Cost_with_colon: "Cost:",
‎   Discount_with_colon: "Discount %:",
‎   SHARE: "SHARE",
‎   EXIT: "EXIT",
‎   cancel_booking: "Do you want to cancel this booking?",
‎   cancel_booking2: "You cannot cancel a completed booking",
‎   Cancel_notification: "Booking cancelled!",
‎   Cancel_notification2: "Booking cancelled!",
‎   NOTIFICATION1: "NOTIFICATION",
‎   No_notification: "No notification!",
‎   RESERVATION: "BOOKING",
‎   LOCKED: "LOCKED",
‎   NO_SHOW: "NO SHOW",
‎   CLICK_TO_SCAN_RESERVATION_CODE: "SCAN BOOKING CODE",
‎   NO_RESERVATION_CODE_SCANNED: "This code cannot be scanned!",
‎   Fetching_data: "Fetching data . . .",
‎   RESERVATION_CODE_SCANNED: "Booking code scanned!",
‎   ALLOT_RESERVATION: "ALLOT BOOKING",
‎   RESERVATION_IS_ALLOTED: "Booking is allotted!",
‎   Click_lock_or_release: "Click to LOCK or CANCEL a booking",
‎   AVAILABLE: "AVAILABLE",
‎   Cannot_lock_or_release: "Cannot lock or release this slot!",
‎   LOCK: "LOCK",
‎   RELEASE: "RELEASE",
‎   Qty_with_colon: "Count:",
‎   Locked1: "Locked",
‎   to: " to ",
‎   NoShow: "No Show",
‎   Cancel_notification3: "Booking cancelled!",
‎   Rate: "Rate",
‎   Rate_your_experience: "Rate your experience",
‎   Payment: "PAYMENT",
‎   Quota: "Quota",
‎   Used: "Used",
‎   Pay: "Pay",
‎   Reservations: "Bookings",
‎   CONFIRM: "CONFIRM",
‎   Description_with_colon: "Description:",
‎   Quota_added: "Bookings credited:",
‎   Transaction_reference: "Transaction reference:",
‎   Paid: "Paid",
‎   Pending: "Pending",
‎   Failed: "Failed",
‎   Design: "Design",
‎   Morning: "Morning",
‎   Evening: "Evening",
‎   Language: "Language",
‎   Software: "Software",
‎   Consultation: "Consultation",
‎   Scan1: "Scan",
‎   Test: "Test",
‎   Purchase: "Purchase",
‎   Staff: "Team member",
‎   Slot: "Slot",
‎   No_payment_data_available: "Uh-oh! There is nothing in here.",
‎   Slot_Available: "Slot Available",
‎   and: "and",
‎   ALL: "ALL",
‎   blank: "Cannot be empty",
‎   invalid: "Data is not complete",
‎   minmaxpassword: "Should have 10 to 36 characters with lower case letters, upper case letters, numbers, and special characters",
‎   mismatch: "Should match with the password",
‎   inuseemail: "📧Contact email",
‎   unverified: "Email is not verified",
‎   incorrect: "Email or password is incorrect",
‎   unregistered: "Email is not registered",
‎   minmaxphone: "Should have 6 to 16 digits",
‎   inusebname: "Someone else has used this gallery name",
‎   selectstartdate: "Select a date",
‎   selectenddate: "Select a date",
‎   agentemail: "Agent and admin emails cannot be the same",
‎   uploadlogo: "Upload gallery logo",
‎   uploadimage: "Upload at least one image",
‎   slottimeless: "Start time should be less than End time",
‎   slottimeequal: "Start and end times cannot be the same",
‎   duplicate: "Data already exists",
‎   itemname: "Select at least one here",
‎   minmaxcount: "Should be less than 100,000",
‎   numonly: "Cannot have decimal numbers",
‎   countmore: "Cannot be 0 or greater than the availablity",
‎   limitmore: "Cannot be 0 or greater than the availability",
‎   Select_one: "Select at least one here",
‎   numdeconly: "Should be a number with two decimals",
‎   minmaxcost: "Should be less than 100,000",
‎   minmaxdiscount: "Should be between 0 and 100",
‎   selecttemplate: "Select a banner",
‎   requestcancelled: "User cancelled request",
‎   signincancelled: "Sign in action cancelled",
‎   backpressed: "Back button is pressed",
‎   Outlet: "Outlet",
‎   Store: "Store",
‎   Shop: "Shop",
‎   Fashion: "Fashion",
‎   Shopping: "Shopping",
‎   Item: "Item",
‎   Shopping_time: "Shopping time",
‎   availabilitychanged: "Someone else booked your selection.\nYour booking may be incomplete.",
‎   statuschanged: "The status of this booking is already updated",
‎   Online: "Online",
‎   Offline: "Offline",
‎   Readymade: "Ready-made",
‎   Custommade: "Custom-made",
‎   Bulkorder: "Bulk order",
‎   Model: "Model",
‎   Group: "Group",
‎   Individual: "Individual",
‎   Single: "Single",
‎   Package: "Package",
‎   Call: "Call",
‎   Agent: "Agent",
‎   App_is_under_maintenance: "App is under maintenance. Try later",
‎   UPDATE: "UPDATE",
‎   versionavailable: "New version of the app is now available!",
‎   DOWNLOAD: "DOWNLOAD",
‎   CART1: "CART",
‎   wrongimageformat: "Image must be .png or .jpeg",
‎   Takeaway: "Takeaway",
‎   Pickup: "Pick up",
‎   CLEAR: "CLEAR",
‎   Select_your_address: "Location",
‎   No_address_selected: "Not available",
‎   Default: "Regular",
‎   Free_text: "Additional comment",
‎   Address_selected: "Location",
‎   Accessory: "Accessory",
‎   Book2: "Book",
‎   businesses: "galleries",
‎   CHANGE: "CHANGE",
‎   Minimum_Billing: "Minimum bill",
‎   No_additional_comments: "No additional comments",
‎   Type_discount_or_Max_Discount_or_both: "Set discount %, or discount limit, or both",
‎   cannot_be_0: "Leave it empty instead of 0",
‎   discount_or_maxdiscount_is_required: "At least one of these values is mandatory",
‎   Must_be_greater_than_Max_discount: "Should be greater than the discount limit",
‎   Release_offer: "Cancel the bookings with this offer and then try again",
‎   Active: "Active",
‎   Inactive: "Inactive",
‎   minbill_optional_for_discountonunit: "Set unit cost, or minimum bill",
‎   minbill_mandatory_for_discountonbill: "Minimum bill is mandatory",
‎   Minimum_Unitcost: "UNIT COST",
‎   Select_eligibleunits: "SELECT ELIGIBLE UNITS",
‎   promo_offer: "Promotion only",
‎   discount_on_unit: "Discount on specified units",
‎   discount_on_bill: "Discount on total bill value",
‎   minucost_or_minbilling_is_allowed: "Only one of these values is required",
‎   Offer_minunitcost: "Minimum unit cost",
‎   Offer_minbill: "Minimum bill",
‎   Cost: "Cost",
‎   Usage_note5: "yet to use",
‎   You_will_pay: "You will pay",
‎   Offer_on_unit: "Discount",
‎   NotBooked: "NOT BOOKED",
‎   Not_booked: "Not booked",
‎   YOUR_ORDER: "MY ORDER",
‎   Description: "Description",
‎   Suite: "Suite",
‎   Enter: "Enter",
‎   Extend_bookings_close_date: "Booking dates have expired. Extend the date.",
‎   MANAGE_RESERVATION1: "BOOKINGS / ORDERS",
‎   Customer_pay: "Guest will pay",
‎   Customer_save: "Guest will save",
‎   Saved_Locations: "Saved locations",
‎   STATISTICS: "STATISTICS",
‎   VIEW_UNIT_BOOKING: "MEMBER-BASED BOOKINGS",
‎   BIRDS_EYE_VIEW: "BIRDS EYE VIEW",
‎   ViewUnits_Intro_Message: "Bookings assigned to the team",
‎   Scan_Intro_Message: "Scan a booking code",
‎   Birdseye_Intro_Message: "Overview of bookings",
‎   Statistics_Intro_Message: "Numbers & Graphs",
‎   VIEW_FULL_BOOKING: "ALL BOOKINGS",
‎   ViewFullBookings_Intro_Message: "List of all bookings",
‎   UNITS: "UNITS",
‎   CUSTOMERS: "GUESTS",
‎   Special_package: "SPECIAL PACKAGE",
‎   Sign_in_with_apple: "Sign in with apple",
‎   Sign_up_with_apple: "Sign up with apple",
‎   Country: "Country",
‎   City: "City",
‎   County: "County",
‎   District: "District",
‎   pinzip: "PIN/ZIP",
‎   Offer1: "Offer",
‎   Report: "Report",
‎   Agent_home: "AGENT HOME",
‎   Add_agent: "ADD AGENT",
‎   Update_agent: "UPDATE AGENT INFO",
‎   STAFF_VIEW: "TEAM VIEW",
‎   FULL_VIEW: "FULL VIEW",
‎   SCAN_NEW_CODE: "SCAN A NEW CODE",
‎   BOOKING_DETAILS: "BOOKING DETAILS",
‎   Do_you_want_to_calloff: "Do you want to cancel this booking?",
‎   Billable_unit: "Billable unit",
‎   Number_of_billable_units: "Number of billable units",
‎   Price_per_billable_unit: "Price per billable unit",
‎   Reservation1: "Booking",
‎   Booking1: "Booking",
‎   Bookings: "Bookings",
‎   BOOKING: "BOOKING",
‎   Business_data_retention: "Gallery data will remain our system for 12 months",
‎   Item_update_timedelay: "Changes will apply in few minutes",
‎   NOTVERIFIED: "NOT VERIFIED",
‎   VERIFIED: "VERIFIED",
‎   Account_Created: "Active from:",
‎   Consumer: "Guest",
‎   SAVE: "SAVE",
‎   No_website_found: "Website not available",
‎   Home_Text1: "Login to JiffyBook",
‎   Home_Text2: "Login with your email",
‎   Home_Text3: "Login to start exploring!",
‎   Optometrist: "Optometrist",
‎   View_templates: "View banners",
‎   Templates: "BANNERS",
‎   View_discount: "View promotion",
‎   Add_template: "ADD BANNER",
‎   Delete: "DELETE",
‎   Submit: "SUBMIT",
‎   Edit_Country: "UPDATE COUNTRY INFO",
‎   Connected_account: "Connected account",
‎   Activate: "ACTIVATE",
‎   Deactivate: "DEACTIVATE",
‎   Created_on: "Created on",
‎   Agent_registered: "Agent is already registered",
‎   Enter_email_alert: "Enter Email",
‎   Templatename_exist: "Banner name already exists",
‎   Edit: "EDIT",
‎   Country_exist: "Country already exists",
‎   Add_country: "ADD COUNTRY",
‎   Select_Country: "Select country",
‎   Country_home: "COUNTRY HOME",
‎   Scheme: "SCHEME",
‎   Banner: "BANNER",
‎   Do_you_want_to_addcountry: "Do you want to add the country?",
‎   Do_you_want_to_activate: "Do you want to activate?",
‎   Do_you_want_to_deactivate: "Do you want to deactivate?",
‎   Do_you_want_to_changecountry: "Do you want to change the country?",
‎   numOrd: "COUNT",
‎   Logo_image: "LOGO",
‎   Profile_picture: "BANNER",
‎   Catalogue_image: "UNIT IMAGE",
‎   Add_segment: "ADD SCHEMA",
‎   Enter_Template: "BANNER NAME",
‎   Edit_segment: "UPDATE SCHEMA INFO",
‎   Video_call: "Video Call",
‎   Whatsapp_call: "WhatsApp Call",
‎   Zoom_call: "Zoom Call",
‎   Googlemeet_call: "Google Meet Call",
‎   Teams_call: "Microsoft Teams Call",
‎   Banker: "Banker",
‎   Organizer: "Organizer",
‎   Meetup: "Meet Up",
‎   Meet_at_a_location: "Meet at a Location",
‎   Interview: "Interview",
‎   HelpSupport: "Help & Support",
‎   EUR: "€",
‎   INR: "₹",
‎   GBP: "£",
‎   USD: "$",
‎   Someone: "Someone",
‎   My_upcoming_bookings: "My bookings",
‎   See_booking_history: "See all bookings",
‎   Add_more_favorites: "Add more favorites",
‎   Add_favorites: "Search galleries",
‎   Search_distance: "Search distance",
‎   SEARCH: "SEARCH",
‎   Import_contacts: "Import phone contacts",
‎   Add_customer: "ADD GUEST",
‎   MANAGE_CUSTOMER: "GUESTS",
‎   No_business_favorites: "Uh-oh! There is nothing in here.",
‎   DELETE: "DELETE",
‎   Delete_question: "Do you want to delete this information?",
‎   Customer_added: "Guest creation date",
‎   First_business_transaction: "First interaction",
‎   Last_business_transaction: "Latest interaction",
‎   Customer_list_empty: "Uh-oh! There is nothing in here.",
‎   Manage_Cust_Heading: "GUEST LIST",
‎   OR_Import_contacts: "Import from contacts",
‎   Add_customer_manually: "Add guest with email, or phone number, or both",
‎   Lead_Time: "Lead time",
‎   minmaxleadtime: "This must be between 1 & ",
‎   Status_by_lead_time: "Within the lead time, this item will be:",
‎   Days: "Day(s)",
‎   Hours: "Hours",
‎   Minutes: "Minutes",
‎   Delivered: "Delivered",
‎   Shipped: "Shipped",
‎   Packed: "Packed",
‎   Prepared: "Prepared",
‎   Stock_Booking: "Products",
‎   Slot_Booking: "Services",
‎   Select_Stock_or_Slot: "Select the gallery type",
‎   Stock_Booking_Message: "This gallery will have catalog of products",
‎   Slot_Booking_Message: "This gallery will have catalog of services",
‎   Add_a_photo: "Add a photo",
‎   Last_stock_updated_on: "Date",
‎   Last_stock_updated: "Latest stock update",
‎   Updated_by: "Team member",
‎   Stock_available_now: "Available quantity",
‎   Add_stock: "Add quantity",
‎   Remove_stock: "Remove quantity",
‎   OR: "OR",
‎   Either_add_or_remove: "Either add or remove",
‎   Remove_less_than_availability: "Cannot remove more than the availability",
‎   Count_0: "Cannot be 0",
‎   Select_working_days: "SELECT WORKING DAYS",
‎   Autoextend_enddate: "Extend window automatically",
‎   _1day: "1 day",
‎   _2day: "2 days",
‎   _7day: "7 days",
‎   _15day: "15 days",
‎   _30day: "30 days",
‎   Booking_window: "BOOKING WINDOW LENGTH",
‎   Order_limit_per_slot: "ORDER LIMIT",
‎   Time_of_delivery: "Delivery in",
‎   Time_of_shipping: "Shipping in",
‎   Time_of_packing: "Packing in",
‎   Time_of_preparation: "Preparing in",
‎   No_current_offername: " ",
‎   No_current_offerdesc: " ",
‎   Service_type_stock: "When will you process an order?",
‎   SameDayService_Active: "During a time slot selected by the guest",
‎   SameDayService_Inactive: "During any working hour within the lead time",
‎   SameDayService_Instant: "During the next working hour",
‎   Instant: "Instant",
‎   Available: "Available",
‎   Unavailable: "Unavailable",
‎   Service_type_slot: "What will a guest receive in a selected time slot?",
‎   Book_Person: "Access to a person or a unique object",
‎   Book_Service: "Access to a service",
‎   Person: "Person",
‎   Remove_from_favorites_question: "Do you want to leave this gallery?",
‎   Select_your_phone: "📞Your phone number",
‎   Select_your_email: "📧Your email address",
‎   Not_added_to_cart: "This cannot be added to the cart",
‎   Added_to_cart: "Added to cart",
‎   Delivery_slots_full: "There are no free slots",
‎   DELIVER_SERVICES: "DELIVER",
‎   Delivery_View: "DELIVER",
‎   PREPARE_ORDER: "PREPARE (View-1)",
‎   Prepare_View: "PREPARE",
‎   OK: "OK",
‎   Do_you_want_to_update_question: "Do you want to save?",
‎   Prepare_Stock1_text: "- from the catalog list -",
‎   Select_a_delivery_date: "Delivery date",
‎   Prepare_Stock1: "PREPARE",
‎   Delivery_Stock1: "DELIVER",
‎   Delivery_Stock1_text: "- from the ready orders -",
‎   Load: "Open",
‎   Orders: "Orders",
‎   Complete: "🏆Complete",
‎   Order_ready: "Ready",
‎   Service_complete: "Complete",
‎   Order_pending: "Pending",
‎   Select_applicable_days: "DE-SELECT UNAVAILABLE DAYS",
‎   Min_1_Max: "This must be between 1 & ",
‎   Prepare_Stock2: "PREPARE",
‎   Delivery_Stock2: "DELIVER",
‎   Delivery_Stock2_text: "Complete an order",
‎   Prepare_Stock2_text: "Make an order ready",
‎   My_favorites: "My favorites",
‎   Booking_start: "GALLERY CREATION DATE",
‎   Search_business: "Search a JiffyGallery",
‎   Search: "Search",
‎   Contact: "CONTACT",
‎   Location: "LOCATION",
‎   Invites_you_to_its_new_adventure: "is in JiffyBook!",
‎   Invitation_mail_body: "Unlock a world of benefits!",
‎   Invitation_mail_body_share: "Place your bookings or orders in the JiffyBook app.",
‎   Regards: "Thanks,",
‎   Added_you_to_its_community: "is in JiffyBook!",
‎   Added_favorites_mail_body: "Hi there!<br><br>You are now in the guest list of this gallery.<br><br>Visit the gallery in the JiffyBook app.",
‎   Login_location: "LOCATION",
‎   Delete_message3: "This is heartbreaking😢",
‎   Delete_message4: "Do you really want to delete your account? This will disconnect your Apple ID from JiffyBook.\n To read what data will be deleted, read the Terms & Policy.",
‎   Contact_email: "📧Contact email",
‎   Import_contacts_do_you_want_to_popup: "Do you want to add the selected contacts to the guests list?",
‎   Ready: "Ready",
‎   READY: "READY",
‎   Working_hours: "Working hours",
‎   Basic_2: "As you use",
‎   GUEST_DETAILS: "GUEST DETAILS",
‎   GALLERY_DETAILS: "GALLERY DETAILS",
‎   Phone_selected: "📞Phone number",
‎   Email_selected: "📧Email",
‎   COMPLETE: "🏆COMPLETE",
‎   COMPLETED: "🏆COMPLETED",
‎   Completed: "🏆Completed",
‎   Bill: "Bill",
‎   NickName: "👤NICKNAME",
‎   INFO: "INFO",
‎   IMAGES: "IMAGES",
‎   CUST_PAYMENT: "PAYMENTS",
‎   CONTACTS: "CONTACTS",
‎   Manager: "Manager",
‎   Owner: "Owner",
‎   PayCard: "Pay by card",
‎   Guest: "Guest",
‎   Service_time: "Service time slot",
‎   Service_location: "Service location",
‎   Women: "Women",
‎   Men: "Men",
‎   Handmade: "Handmade",
‎   Takeout: "Takeout",
‎   PayReceived: "Payment Received",
‎   Courier: "Courier",
‎   Product_delivery: "Product Delivery",
‎   HomeDecor: "Home Decor",
‎   Guests: "Guests",
‎   Unpaid: "Payment pending",
‎   Purchase_Order: "Purchase Order",
‎   Appointment_Request: "Appointment Request",
‎   Confirmed: "Confirmed",
‎   Confirmed1: "CONFIRMED",
‎   Custom_Product: "Custom Product",
‎   Decoration: "Decoration",
‎   Visit_our_gallery: "Visit us in JiffyBook.",
‎   Digital_space_for_galleries_of_products_and_services: "Digital space for galleries of products and services",
‎   REFERENCE: "REFERENCE",
‎   Max6: "Limit: 6 characters",
‎   Reference: "Reference",
‎   Select_start_end_time: "Select start time and end time",
‎   Cancelled_by_Consumer: "Cancelled by the guest",
‎   Cancelled_by_Business: "Cancelled by the gallery",
‎   Basic_details: "Basic Details",
‎   You_cannot_change_these_details_in_the_future: "You cannot change these details in the future",
‎   Rate_to_earn_rewards: "Did you like this?\nClick here to rate your experience\n⭐✨🌟",
‎   Delivery: "Delivery",
‎   Value_for_money: "Value for money",
‎   Quality: "Quality",
‎   Select_service: "Select service",
‎   Applicable_on: "Applicable on",
‎   Total_bill: "Total bill amount",
‎   Full_Successful_booking_message: "The booking was successful.",
‎   Partial_Successful_booking_message: "Please wait . . .",
‎   Failed_booking_message: "But the booking was not successful. Try again.",
‎   Booking_details_are_in_the_home_or_email: "You can find the details in your bookings tab, or in your email inbox.",
‎   Thank_you_for_the_order: "Thanks!",
‎   Uh_oh: "Uh-oh!",
‎   Conatct_Prominent_Disclosure_Heading: "Disclosure about the data collected",
‎   Business_Prominent_Disclosure_Heading: "JiffyBook collects and stores your:\n\n👉Email address\n(for login & communication)\n\n👉Location & Phone number\n(for product/service delivery)\n\n👉Media\n(if you choose to post them)\n\n👉Contacts\n(if you choose to invite others)",
‎   Rating_successfully_done: "Your rating has been posted.\nThank you!",
‎   Communication_email: "📧COMMUNICATION EMAIL",
‎   Workflow: "Workflow",
‎   Verifcation_code: "Verification code",
‎   Cannot_be_rated: "This cannot be rated.",
‎   Account_email: "📧ACCOUNT EMAIL",
‎   Clothing: "Clothing",
‎   WORKFLOW: "WORKFLOW",
‎   Ontime: "In time",
‎   Closed: "Closed",
‎   CLOSED: "CLOSED",
‎   Share_email: "Share email with gallery",
‎   Shares_email: "Shares email with guests",
‎   Share_email_phone: "Share email and phone number with gallery",
‎   Shares_email_phone: "Shares email and phone number with guests",
‎   Share_email_phone_address: "Share email, phone number and address with gallery",
‎   Shares_email_phone_address: "Shares email, phone number and address with guests",
‎   Share_email_address: "Share email and address with gallery",
‎   Shares_email_address: "Shares email and address with guests",
‎   Share_phone_address: "Share phone number and address with gallery",
‎   Shares_phone_address: "Shares phone number and address with guests",
‎   Share_email_phone_address_comment: "Share email, phone number, address and additional notes with gallery",
‎   Share_email_address_comment: "Share email, address and additional notes with gallery",
‎   Share_phone_address_comment: "Share phone number, address and additional notes with gallery",
‎   Share_address_comment: "Share address and additional notes with gallery",
‎   Share_phone_comment: "Share phone number and additional notes with gallery",
‎   Share_email_comment: "Share email and additional notes with gallery",
‎   Share_phone: "Share phone number with gallery",
‎   Shares_phone: "Shares phone number with guests",
‎   Share_address: "Share address with gallery",
‎   Shares_address: "Shares address with guests",
‎   Share_comment: "Share additional notes with gallery",
‎   New_arrivals_delivery_pickup: "New arrivals - delivery and pickup",
‎   Order_clothing_from_catalog: "Order clothing from a catalog",
‎   Chat_with_gallery: "Chat with gallery",
‎   Bookings_disabled: "Bookings disabled",
‎   Bookings_open_1day: "Bookings open for 1 day",
‎   Bookings_open_2days: "Bookings open for 2 days",
‎   Bookings_open_3days: "Bookings open for 3 days",
‎   Bookings_open_1week: "Bookings open for 1 week",
‎   Bookings_open_15days: "Bookings open for 15 days",
‎   Bookings_open_1month: "Bookings open for 1 month",
‎   Bookings_open_anytime: "Bookings open anytime",
‎   booking_closed_by_gallery: "Gallery bookings are closed",
‎   Dresses: "Dresses",
‎   Abaya: "Abaya",
‎   Burqa: "Burqa",
‎   Hijab: "Hijab",
‎   ratings: "reviews",
‎   Click_to_accept: "Click here to accept",
‎   Use_rewards: "Use JiffyGoldies",
‎   Jiffyrewards: "JiffyGoldies:",
‎   Balance: "Balance:",
‎   Level: "Level:",
‎   Jiffyrewards1: "JiffyGoldies",
‎   ServiceCost: "Service Cost",
‎   Cost2: "Cost including taxes",
‎   Select_item_size: "Available variants",
‎   No_match_found: "Not found",
‎   Admin1: "Admin",
‎   PREPARE_ITEMVIEW: "PREPARE\nITEM VIEW",
‎   PREPARE_ORDERVIEW: "PREPARE\nORDER VIEW",
‎   Select_item_length: "Available labels",
‎   Select_item_material: "Available labels",
‎   Select_custom_category: "Available labels",
‎   Swipe_for_more: "Swipe and select",
‎   Select_labels: "Label selection is mandatory",
‎   Manage: "Manage",
‎   Filter: "Filter",
‎   Refresh: "Refresh",
‎   Cart: "Cart",
‎   JIFFYGALLERY_INVITATIONS: "JIFFYGALLERY INVITATIONS",
‎   ACCEPT_INVITATION: "ACCEPT INVITATION",
‎   Refer_Earn_Goldies_Per_Order: "Refer others and earn goldies for every order made by them",
‎   ReferralCode: "Referral Code",
‎   CouponCode: "Coupon Code",
‎   Apply1: "APPLY",
‎   MoreInfo: "More info",
‎   Select1: "SELECT",
‎   Self: "Self",
‎   OtherDetails: "Check other details",
‎   Join1: "JOIN",
‎   MaxAllowedGoldies: "Claimed in this booking:",
‎   PREPARE_ORDER1: "PREPARE (View-2)",
‎   Prepare_Stock1_text1: "- from the order list -",
‎   More: "More",
‎   Add_to_favorites_question: "Add this gallery to the favorites?",
‎   Added_to_favorites: "You can now see this gallery in your favorties.",
‎   Web: "Web",
‎   Finalize_order: "Finalize your order",
‎   Save1: "Save",
‎   Remove: "Remove",
‎   Selection: "Selection",
‎   Make_selection: "Make your selection",
‎   Pick_variant: "Pick a variant",
‎   Pick_label: "Pick labels",
‎   Enter_Available: "Enter availability",
‎   Digital_space_for_galleries_of_genuine_brands: "Digital Space for Galleries\nof Genuine Brands",
‎   Login_signup_terms_policy_disclaimer: "By logging in or signing up, you confirm that you agree to the latest JiffyBook Terms and Policy",
‎   Create_account_email: "Create an account with your email",
‎   JiffyGallery_Manager: "JiffyGallery Manager",
‎   Day: "Day",
‎   Day_Days: "Day/Days",
‎   Login_with_email: "Login with email",
‎   ViewMyGoldies: "Goldies",
‎   Villa: "Villa",
‎   Estate: "Estate",
‎   Castle: "Castle",
‎   Palace: "Palace",
‎   Fortress: "Fortress",
‎   Citadel: "Citadel",
‎   Kingdom: "Kingdom",
‎   VillaMember: "Villa member",
‎   EstateMember: "Estate member",
‎   CastleMember: "Castle member",
‎   PalaceMember: "Palace member",
‎   FortressMember: "Fortress member",
‎   CitadelMember: "Citadel member",
‎   KingdomMember: "Kingdom member",
‎   Member: "Member",
‎   Member1: "member",
‎   Soldout1: "SOLD OUT",
‎   Allgalleries: "Other galleries",
‎   Add_a_video: "Add a video",
‎   Add_photos: "Add photos",
‎   Type_of_promotion: "Type of promotion",
‎   Add_catalog1: "ADD CATALOG",
‎   Number_of_Sections: "Number_of_Sections",
‎   Hide: "Hide",
‎   Activate_catalog_question: "Activate this catalog?",
‎   Show_catalog_question: "Show this catalog to guests?",
‎   Enable_catalog_order_question: "Allow users to order from this catalog?",
‎   Dashboard: "Dashboard",
‎   Catalog1: "Catalog",
‎   Catalog_units: "Catalog units",
‎   Dress_color: "Fabric color",
‎   Embroidery: "Embroidery",
‎   Embroidery_color: "Embroidery color",
‎   Embroidery_type: "Design ideas",
‎   Position: "Embroidery position",
‎   Create_my_AiAbaya: "Create my Ai Abaya",
‎   Try_another_design: "Try another design",
‎   Start_over: "Start over",
‎   Type: "Type",
‎   Size: "Size",
‎   Sky_is_the_limit: "Love this? Order this from us. Or add it to your wishlist to order later.",
‎   Creating_my_Ai_Abaya: "Creating my Ai Abaya ...",
‎   Order_my_Ai_Abaya: "Order my Ai Abaya",
‎   Try_4_more_design: "Try 4 more designs",
‎   Try_3_more_design: "Try 3 more designs",
‎   Try_2_more_design: "Try 2 more designs",
‎   Try_1_more_design: "Try 1 more designs",
‎   No_more_designs: "No more designs",
‎   You_have_exceeded_your_quota: "Place an order from your drafted designs to initiate production.",
‎   Waiting_time: "Waiting time",
‎   wishlist: "Wishlist",
‎   open_wishlist: "Open wishlist",
‎   Order_from_wishlist: "Order from wishlist",
‎   Remove_an_image_from_the_wishlist: "Wishlist is full. Remove an item to continue adding.",
‎   Already_added_to_wishlist: "This is in the wishlist already!",
‎   No_Wishlist: "Uh-oh! There is nothing in here.",
‎   Select_from_wishlist: "Select and scroll down to order",
‎   Try_again_colon: "Try again:",
‎   Designs: "design(s)",
‎   CustomAIBooking: "Ai Orders",
‎   RegularBooking: "Regular Orders",
‎   Confim_Stock1: "PREPARE",
‎   Confim_Stock1_text: "Internal preparation phase",
‎   Confim_Stock2: "DELIVER",
‎   Confim_Stock2_text: "Customer delivery phase",
‎   CONFIM_ORDER: "DELIVERIES",
‎   Select_delivery_date: "Preparing for delivery",
‎   out_of_delivery: "Delivery in progress",
‎   Open_catalog: "Open catalog",
‎   Order_now: "Order now!",
‎   PREPARE_MyView: "PREPARE\n(My View)",
‎   DELIVERY_MyView: "DELIVER\n(My View)",
‎   PREPARE_MyView_text: "Preparations assgined to me",
‎   DELIVERY_MyView_text: "Deliveries assigned to me",
‎   Assign_Location_question: "Assign location to this user",
‎   Location_name: "Location name",
‎   Delivery_by: "Delivery by:",
‎   Archived: "Archived",
‎   Dossier: "Collection",
‎   Order_this: "Order this",
‎   Ai_abaya: "Ai Abaya",
‎   Jewels_ai: "Jewels Ai",
‎   Doubleclickzoom_Swipedownclose: "Dobule-click to Zoom & Swipe down to close",
‎   Add_to_Wishlist: "Add to Wishlist",
‎   Added: "Added",
‎   Create_my_AiDesign: "Create my Ai Design",
‎   TypeCost: "Type Cost",
‎   Order_my_Ai_Design: "Order my Ai Design",
‎   Open_detailed_view: "Open detail view",
‎   Snapshot: "Snapshot",
‎   Unit_bookings: "Unit bookings",
‎   Create_Business: "ADD JIFFYGALLERY",
‎   View_Business_Dashboard: "View dashboard",
‎   View: "View",
‎   Number_of_Trial_Limit: "Designs you can draft:",
‎   Select_a_business: "Select a gallery",
‎   DesignCost: "Design Cost",
‎   Pick_a_scene: "Pick a scene",
‎   Ai_Design_Cost: "Design Cost",
‎   Total: "Total",
‎   countdown_text: "Generating your dream design within a minute,\nlike never before!",
‎   Create_my_AiOffer: "Create a promotion with Ai",
‎   This_order_is_fulfilled_by: "This order is fulfilled by:",
‎   Country_of_origin: "Country of origin:",
‎   Warranty: "Warranty:",
‎   Importer: "Importer:",
‎   Click_to_open_gallery_legal: "Click to read our terms and policies",
‎   I_agree_to_the_Privacy_Policy: "I agree to JiffyBook's Privacy Policy",
‎   I_agree_to_the_Terms_of_Service: "I agree to JiffyBook's Terms",
‎   User_this: "Use this",
‎   OrderID: "Order ID:",
‎   Enable_during_checkout: "Enable during checkout",
‎   Enter_valid_format_3dec: "Enter in correct format (12.345)",
‎   Enter_valid_format_2dec: "Enter in correct format (12.34)",
‎   Discovery_feed: "BRANDS I LOVE",
‎   Ai_Generated: "AI-generated",
‎   Add_quotation: "Add pricing to proceed",
‎   Incentivised_rating: "This is an incentivised rating",
‎   Added_to_wishlist: "Added to your wishlist!",
‎   Failed_to_download: "Failed to download. Try again",
‎   Image_saved_succesfully: "Image saved successfully",
‎ };